### ISSUE TITLE
Issues to be resolved for a new PR on weather models GMAO and MERRA-2

### ISSUE THREAD

**Issue by leiyangleon** [dbekaert/RAiDER#103]
@jlmaurer @dbekaert Please review below the list of issues or temporary fixes so that I can issue a new PR on the newly added weather models GMAO and MERRA-2. Please let me know what you think for each of these points and if there is any action needed.

(_PS: I sent you guys messages in my weekly project report and slack but haven't heard from you yet. I need your opinions to finalize the changes or refine them before issuing a new PR._)

 ### Version inconsistency of RAiDER (w.r.t. the use of weather models GMAO and MERRA-2):

Two versions compared: June 23 (old) vs July 28 (new)

1. In the final delay results derived from the GMAO model, the new version has pixels (as @jlmaurer  mentioned, this could be waterbodies) masked out, while the old version retained those pixels.
2. The first TWO example commands (calling raiderDelay.py) from the helper message failed in the new version while succeeded in the old one. The third example command works for both versions though.

### Lag time issues w.r.t. the weather models GMAO and MERRA-2

1. Both GMAO and MERRA-2 use utc time zone, while the weather model base class assumes the lag time check is in the time zone where the user is located not the UTC zone. Currently, I modified the weather model base class to use UTC time zone for the lag time [check](https://github.com/leiyangleon/RAiDER/blob/1dbe783a8b91ebd74e0c9e51f8527d8f8dcf12d2/tools/RAiDER/models/weatherModel.py#L247-L252), as required for the GMAO and MERRA-2 models. But it might be useful to unify the time zone for all weather models. 

2. GMAO lag time is not 7.5 hrs as far as I notice, rather, it is only available up to 3am UTC every day. For example, assuming we want July 30 2020 12:00:00 PST, that is July 30 2020 19:00:00 UTC, the data server only stores data up to July 30 2020 03:00:00 UTC. Currently, we have 7.5 hrs hardcoded, but might want to update it. Otherwise, it will export errors when it couldn’t find the data.

3. MERRA-2 lag time is also tricky. It is not released on the 1 st day of each month, rather, in the middle of each month, which also varies month to month (from the 11 th to 21 st ). When the data was released, it releases the data for the whole past month. So, to make sure no error messaged is exported, we do the following for now: assuming we want July 20 2020, we will put the valid range up to May 30, although the June data could have been released already but it also could not. So in this way we don’t trigger errors when the June data has not been released.

**Comment by dbekaert** [comment]
hi @leiyangleon could you perhaps clarify which items are fixed and which are to be addressed?
I suggest for those outstanding separate issue tickets to be generated such they can be fixed.
i.e. i understand that the first two items are open issues?


wrt lag issues:
- that sounds good.
- I have emailed GMAO team to get you that information, you were copied in CC.
- ok that should be fine for now. Probably we should also have a check in the code when models are trying to be downloaded to a file that does not exist, it provides a warning and TBD if we just eliminate the epic and continue with those that exist or if we error out altogether whcih goes into the loggers. How are you currently handling an error in e.g. pydab if the files does not exixt? Similar for the csdapi does it provide you some insight if a files does not exist?

**Comment by leiyangleon** [comment]
@dbekaert sounds good. Below I have action items marked explicitly. Most of the action items for you and @jlmaurer are only to confirm (except 2nd bullet in version inconsistency) and I will do the rest. Please let me know when you have a chance.

Version inconsistency:

1.	Probably not a bug: by running the following example command
`raiderDelay.py --date 20200103 --time 23:00:00 --latlon test/scenario_1/geom/lat.dat test/scenario_1/geom/lon.dat --model GMAO --zref 20000 -v --out test/scenario_1/`
some of the pixels that used to be valid now turn to zeros. **[Action] If both @jlmaurer and @dbekaert  confirm that this is what we decided to do over waterbodies, no need to fix then.** Just want to double check though.

2.	This is a bug: the following two example commands from the raiderDelay.py helper message fail while they used to work for GMAO and MERRA-2 as well as other models.
`raiderDelay.py --date 20200103 --time 23:00:00 -b 40 -79 39 -78 --model GMAO --zref 15000 -v`
`raiderDelay.py --date 20200103 --time 23:00:00 -b 40 -79 39 -78 --model GMAO --zref 15000 --heightlvs 0 100 200 -v`
I don’t think this is due to the GMAO or MERRA-2 model, because the third example command shown above in the 1st bullet works without any problems. **[Action] @jlmaurer  and @dbekaert  please check if there is any error in the recent PR’s.**

Lag time issue:

1.	This is a bug with temporary fix: I assume most (if not all) of weather models use UTC time zone, at least GMAO and MERRA-2. Currently, the lag time is in the user’s local time zone for all other models while in UTC for GMAO and MERRA-2. But do we want to use UTC for the other models otherwise there may be error? **[Action] @dbekaert  and @jlmaurer  please confirm.**

2.	This is a bug: **[Action] I will fix it based on the information from the GMAO team.** 

3.	This is a temporary fix: in this way, the MERRA-2 model data is guaranteed to exist so I haven’t included a check. But this is a useful point. **[Action] I will try to add a data availability check for both OpenDAP and cdsapi.** 
.

**Comment by dbekaert** [comment]
@jlmaurer can you check bullet 2 above. They re part of the circle cii test suite so should have been succesfull or it would have prohibited of merging past PR.

**Comment by leiyangleon** [comment]
@dbekaert @jlmaurer bullet 2 can be fixed by switching to Python interpolator, which is described in a new issue ticket #106 .

**Comment by leiyangleon** [comment]
@dbekaert @jlmaurer I am closing this ticket. Because

Version inconsistency

- ticket #105 is opened to address water masking

- ticket #106 is opened to address the bus/segmentation error (C++ interpolator bug)

Lag time issues

- UTC time zone is now used for all models

- worst case lag time of 24 hrs is used for GMAO to guarantee the date files exist

- MERRA-2 lag time is also calculated dynamically to guarantee the date files exist. Also, ticket #107  is opened for adding model data availability check.

**Comment by jlmaurer** [comment]
@leiyangleon sounds good!
