### ISSUE TITLE
Bus error and/or segmentation fault for the example runs of GMAO and MERRA-2 model 

### ISSUE THREAD

**Issue by leiyangleon** [dbekaert/RAiDER#106]
**Describe bug**

When the size of 3-D data cubes increases to certain value, e.g. 9 x 8 x 72, all three example runs from the helper message (`raiderDelay.py -h`) fail with bus error and/or segmentation fault. If the size is smaller, e.g. 7 x 7 x 72, there is no problem. 

Note this error is only related to GMAO and MERRA-2 model which require the interpolation along vertical axis (could be one  possible reason).

Also, the old version using Python interpolator did not break. 

**Error report**

We only show the GMAO for example. The MERRA-2 has the same problem. Their data readers work just as well as other models by visualizing the p/q/t datasets. So it must be the processing after feeding in the data that gives this error.

GMAO (with size of 13 x 11 x 72) - Fail

```
raiderDelay.py --date 20200103 --time 23:00:00 -b 40 -79 38 -77 --model GMAO --zref 15000 -v
Starting to run the weather model calculation
Time type: <class 'datetime.datetime'>
Time: 20200103
Flag type is bounding_box
DEM/height type is "skip"
Beginning weather model pre-processing
Download-only is False
Storing weather model at: ./weather_files/GMAO_2020_01_03_T23_00_00.nc
Weather model GMAO is available from 2017-12-01 00:00:00-Present
Segmentation fault: 11
```

GMAO (with size of 9 x 8 x 72) - Fail

```
 raiderDelay.py --date 20200103 --time 23:00:00 -b 40 -79 39 -78 --model GMAO --zref 15000 -v
Starting to run the weather model calculation
Time type: <class 'datetime.datetime'>
Time: 20200103
Flag type is bounding_box
DEM/height type is "skip"
Beginning weather model pre-processing
Download-only is False
Storing weather model at: ./weather_files/GMAO_2020_01_03_T23_00_00.nc
Weather model GMAO is available from 2017-12-01 00:00:00-Present
Bus error: 10
```

GMAO (with size of 7 x 7 x 72) - Succeed

 ```
raiderDelay.py --date 20200103 --time 23:00:00 -b 40 -79 39.5 -78.25 --model GMAO --zref 15000 -v
Starting to run the weather model calculation
Time type: <class 'datetime.datetime'>
Time: 20200103
Flag type is bounding_box
DEM/height type is "skip"
Beginning weather model pre-processing
Download-only is False
Storing weather model at: ./weather_files/GMAO_2020_01_03_T23_00_00.nc
Weather model GMAO is available from 2017-12-01 00:00:00-Present
Number of weather model nodes: 1460
Shape of weather model: (4, 5, 73)
Bounds of the weather model: 39.25/40.00/-79.38/-78.12 (SNWE)
Weather model: GMAO
Mean value of the wet refractivity: 11.769009
Mean value of the hydrostatic refractivity: 86.626891

======Weather Model class object=====
Number of points in Lon/Lat = 4/5
Total number of grid points (3D): 1460
Latitude resolution: 0.25
Longitude resolution: 0.3125
Native projection: epsg:4326
ZMIN: -100.0
ZMAX: 15000.0
Minimum/Maximum y:  39.25/ 40.00
Minimum/Maximum x: -79.38/-78.12
Minimum/Maximum zs/heights:    -100.00/  74842.31
=====================================
k1 = 0.776
k2 = 0.233
k3 = 3750.0
Humidity type = q
=====================================
Class name: gmao
Dataset: gmao
=====================================
A: []
B: []

Beginning DEM calculation
Beginning delay calculation
Reference z-value (max z for integration) is . m
Number of processors to use: 1
Delays have been written to the weather model file; see ./weather_files/GMAO_2020-01-03T23_00_00_39.5N_40.0N_-79.0E_-78.25E.h5
```

**Possible fix**

I am going to test the large data size with both C++ and Python interpolators.

**Comment by leiyangleon** [comment]
@Askaholic @dbekaert @jlmaurer after switching to the Python interpolator, the error is fixed. Could @Askaholic take a look and try to address the problem in the C++ interpolator?

**Comment by jlmaurer** [comment]
Just a note @Askaholic and others there are a couple pre-existing interpolation packages in c++ ([linterp](https://rncarpio.github.io/linterp/) and [btwxt](https://github.com/bigladder/btwxt)) that perhaps could be looked at for comparison.

**Comment by Askaholic** [comment]
Yea I might be able to write some wrapper around one of those libraries, but I think either way I'll have to implement `interpolate_along_axis` myself because that doesn't seem to be supported out of the box as far as I can tell. 

I also stumbled upon another library which might potentially be of interest:
https://pangeo-pyinterp.readthedocs.io/en/latest/

@leiyangleon You could also try setting `max_threads=1`. Maybe there is still a problem with the work splitting (it took me a while to get it working in the first place). It only tries to add more threads once there is a large amount of data, so this could be consistent with the observed behavior.
