### ISSUE TITLE
STATS: verify variogram sill

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#11]
The sill value looks off, need to verify what is happening.
![Screen Shot 2020-02-18 at 9 15 26 AM](https://user-images.githubusercontent.com/19240905/74760492-54ed4d80-522f-11ea-847d-023f035cc517.png)

**Comment by dbekaert** [comment]
@sssangha lets go through this together, could be a unit or a scaling issues

**Comment by sssangha** [comment]
Unit error verified. Factor of (10^4) was applied to the sill value. Will push separate PR with fix soon.

**Comment by sssangha** [comment]
Regarding my updates, here is an example of an experimental variogram fit for a single grid-cell:
![grid10_timeslice20180321–20180621_justEXPvariogram](https://user-images.githubusercontent.com/13227405/91025270-ffaf4180-e5ad-11ea-9ea8-0672e2b863db.png)

And the sill values across the entire study area for a given year:
![ZTD_sill_heatmap](https://user-images.githubusercontent.com/13227405/91025316-0ccc3080-e5ae-11ea-9635-568389b4cb6a.png)

Refer to PR #118 for the specific commands you may execute to obtain these plots.
