### ISSUE TITLE
[BUG] Look vectors computed from orbit state are not correct for all lat/lon

### ISSUE THREAD

**Issue by Askaholic** [dbekaert/RAiDER#122]
It seems that some coordinates are using the wrong orbit states from the orbit file. Some of the look vectors are actually pointing into the earth (particularly at the south pole). I'm not entirely sure if this is a bug in the code or just me passing it in bad data, but @jlmaurer recommended that I open an issue.

The orbit file I'm using:
```
S1A_OPER_AUX_POEORB_OPOD_20200123T120833_V20200102T225942_20200104T005942.EOF
```
Reference time is the first time in the file: `UTC=2020-01-02T22:59:42.000000`

The lat/lon coordinates:
```python
llh = np.stack((
    np.arange(-90, 90, 10),
    np.arange(-180, 180, 20),
    np.zeros(18)
), axis=-1)
```

The generated look vectors:
```
[[ 0.03437038 -0.77620184  0.62954697]
 [ 0.0383505  -0.77579979  0.62981262]
 [ 0.0403828  -0.7748323   0.63087569]
 [ 0.03922698 -0.77388994  0.63210411]
 [ 0.03557281 -0.77349198  0.63280703]
 [ 0.03088839 -0.77385543  0.63260864]
 [ 0.0260029  -0.77513055  0.63126578]
 [ 0.02085322 -0.77772672  0.62825655]
 [ 0.01484669 -0.7826475   0.62228809]
 [ 0.00522094 -0.79348542  0.60856686]
 [-0.84752044  0.36413386  0.38615493]
 [-0.90036782  0.43509906  0.00515753]
 [-0.9528133   0.29981533  0.04751404]
 [-0.96379158  0.24163011  0.11278597]
 [-0.79917038  0.39099675  0.45656133]
 [ 0.18492425  0.46336279  0.86665908]
 [ 0.41144342  0.2904851   0.8639055 ]
 [-0.09540875  0.07311706  0.99274925]]
```

Here I've extended the rays out to an altitude of 3000 km so that their direction is easy to see on the plot. The red points are the first 50 orbit locations in the orbit file.
![Screen Recording 2020-08-28 at 3 29 15 PM](https://user-images.githubusercontent.com/17941539/91622441-a2890680-e986-11ea-96f1-504fbbf7c1da.gif)

**Comment by dbekaert** [comment]
@Askaholic could you provide some insight how you call this?

The orbit vector has multiple epics, but we are evaluating it for a fixed time.
So if we are having multiple ground point that cover the complete globe, some would need to be traced through the earth to the target. That said, I would also expect them to intersect then at a given location.
