### ISSUE TITLE
Should cython be a required dependency for RAiDER? 

### ISSUE THREAD

**Issue by jlmaurer** [dbekaert/RAiDER#13]
As opposed to just writing some nice .cpp files and including those. Maybe it makes it easier, or not?

**Comment by dbekaert** [comment]
even if they are c-code programs, would you not use cython wrappers to call them as python functionality?

**Comment by piyushrpt** [comment]
Yeah - we would need either cython / pybind11 to make python talk to C++. Numpy now uses cython to build part of itself - so we should be getting cython functionality at no cost.

**Comment by dbekaert** [comment]
Requirements in README reflect to keep cython and numpy.
Per discussion keeping cython and closing this issues.
