### ISSUE TITLE
STATS: Residual between GNSS and Raider

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#157]
Initially we were appending GPS Raider delays to GPS delay file. Not sure we still have this support for it. Also not sure how this works if raider delays are not sampled on the same time-epics.

Suggest we do the residual calculation from he intersection between the Raider delays and GPS delays within the stats class.
@sssangha @jlmaurer what are your thought as to keep this simple, not require duplication of data etc?
Perhaps a simple mapping of index to raider file and index to GPS file?

**Comment by jlmaurer** [comment]
@dbekaert when I did it before it was entirely manual, in the sense that there was no built-in functionality. I just opened both files in ipython using pandas and did the manipulation myself. 

We could do the manipulation automatically if the data frames are defined as time-series, which can be natively merged in pandas. This would basically require a fixed sampling time with no-data values defined for any missing datetimes. I think this is actually what I did before manually. Then, if columns have standard names, the process is simple to merge the data frames on common times and  calculate the residuals. 

@sssangha does this sound like a viable option? We could write a little cmd-line function that lets a user specify a list of files each containing a standardized column name (e.g. "totaldelay__hrrr_m", then simply merge all those columns into a single data frame and calculate the cross-residuals. Could process results from multiple weather models this way.

**Comment by sssangha** [comment]
@jlmaurer this sounds good. Would of course have to define common timing convention w.r.t. GPS zenith delays so it is seamless to compare them. Also, would be good idea to kick out missing datatimes from dataframes before saving. It makes a huge difference in accessing the data later.

**Comment by dbekaert** [comment]
Just to clarify:
- We can have downloaded GPS at e.g. every 5min for 10 years for a GPS station list
- We can have raider delays e.g. fixed utc time for 10 years for a GPS station list (does not need to be the same)

Steps:
1) intersect the station list; and report those not covered in raider delays, and those not covered in GPS downloaded delays
2) intersect the time-slices now

TBD:
What is the best way of storing this information. i.e. do we track indexes, do we write out a new file etc.

**Comment by dbekaert** [comment]
@sssangha we are pretty close to rely on this component; emailed a link location with a set of CSV files to be concatenated

**Comment by dbekaert** [comment]
@jlmaurer, I tried to run this through @sssangha  code and it fails because of missing column
Suggest you keep your Datetime, so sim can update his code separately.
 
So would say add “Date” and “times”
 
What you generate:
```ID,Datetime,Lat,Lon,Hgt_m,ERA5,ZTD,sigZTD,ERA5_minus_ZTD
02NA,2009-01-01 06:00:00,-12.3559,130.88170000000002,117.652,2.5967504287379555,2.612,0.0023,-0.015249571262044626
0BOD,2009-01-01 06:00:00,57.247,17.058699999999988,45.525,2.3296772272558863,2.346,0.0016,-0.016322772744113756
0LOD,2009-01-01 06:00:00,55.7669,12.995800000000004,56.372,2.3525837075969123,2.3699000000000003,0.0016,-0.017316292403088074
 ```
 
What Sim Assumes:
```ID,Date,ZTD,wet_delay,hydrostatic_delay,times,sigZTD,Lat,Lon,Hgt_m
1LSU,2009-01-01,2.3756,0.0468,2.3288,21600,0.0016,30.4074,-91.1803,-6.487
1LSU,2009-01-02,2.4751,0.1656,2.3095,21600,0.0016,30.4074,-91.1803,-6.487
```

You can test it as:
```
 raiderStats.py --file Combined_delays_ERA5_ZTD.csv -w maps -b '36 40 -124 -119' -ti '2018-01-01 2019-12-31' --seasonalinterval '03-21 06-21' -variogramplot -variogram_per_timeslice --cpus all -verbose -grid_to_raster -c ERA5_minus_ZTD
 ```

**Comment by dbekaert** [comment]
@sssangha @jlmaurer tried the new file you shared:

The content looks good
```
ID,Datetime,Lat,Lon,Hgt_m,ERA5,ZTD,sigZTD,ERA5_minus_ZTD,Date,times
02NA,2009-01-01 06:00:00,-12.3559,130.88170000000002,117.652,2.5967504287379555,2.612,0.0023,-0.015249571262044626,2009-01-01,21600
0BOD,2009-01-01 06:00:00,57.247,17.058699999999988,45.525,2.3296772272558863,2.346,0.0016,-0.016322772744113756,2009-01-01,21600
```

@sssangha i ran the following, any thoughts?:

```
(raider) MT-101939:RAiDER-most-current dbekaert$ raiderStats.py --file Combined_delays_ERA5_ZTD.csv -w maps -b '36 40 -124 -119' -ti '2018-01-01 2019-12-31' --seasonalinterval '03-21 06-21' -variogramplot -variogram_per_timeslice --cpus all -verbose -grid_to_raster -c ERA5_minus_ZTD
***Stats Function:***
***Variogram Analysis Function:***
Traceback (most recent call last):
  File "/Users/dbekaert/Software/python/miniconda37/envs/raider/bin/raiderStats.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderStats.py')
  File "/Users/dbekaert/Software/python/miniconda37/envs/raider/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/dbekaert/Software/python/miniconda37/envs/raider/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/Users/dbekaert/Software/python/miniconda37/envs/raider/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/raiderStats.py", line 41, in <module>
    inps.variogram_per_timeslice
  File "/Users/dbekaert/Software/python/miniconda37/envs/raider/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/statsPlot.py", line 1086, in stats_analyses
    TOT_grids, TOT_res_robust_arr = make_variograms.create_variograms()
  File "/Users/dbekaert/Software/python/miniconda37/envs/raider/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/statsPlot.py", line 488, in create_variograms
    for i in sorted(list(set(self.df['gridnode']))):
TypeError: '<' not supported between instances of 'str' and 'int'
```
