### ISSUE TITLE
Large weathermodel download memory issues

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#158]
Model download challenges when downloading world as all is kept in memory for all variables. Issue for higher res models like HRES. See if we can decrease memory need by more rapidly clearing variables, e.g can be written to file and clear directly before moving to another variable.

**Comment by dbekaert** [comment]
So far it looks we can keep ERA5 in memory when computing delays for the global GPS station list

**Comment by dbekaert** [comment]
HRES fail; memory error could be related to #195

**Comment by jlmaurer** [comment]
Fixed by #234 and #239
