### ISSUE TITLE
pixel node verus pixel center registration of models

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#164]
Currently we write manually to hdf5.
Need to verify if do not make incorrect assumption for the models.
Once we are in netcdf we can let GDAL do the semantics.

**Comment by leiyangleon** [comment]
Verified that by using the new [netcdf4 branch](https://github.com/dbekaert/RAiDER/tree/netcdf4), the coordinate grid in the NetCDF outputs is pixel centered (not top left corner aligned) for all of the weather models (i.e. ERA-5, ERA-5T, ERA-I, HRES, GMAO, MERRA-2, NCMR), and exactly aligned with the coordinate grid in the native weather model data (that are NetCDF files as well)
