### ISSUE TITLE
HRES download failure prior to 2013-06-25 due to different number of model levels

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#168]
I have reached out to ECMWF for guidance and to get insight if the model has some fixed changes in time which we need to account for in the API. Looks like the requested number of variables versus what is expected is not consistent for recent and older HRES data.

![Screen Shot 2020-10-30 at 4 51 21 PM](https://user-images.githubusercontent.com/19240905/97781983-23fa4200-1b4c-11eb-92b8-06d4f9f6ef06.png)

**Comment by dbekaert** [comment]
Heard back from ECMWF helpdesk. 
- Before 2013-06-25, only 91 model levels are available
- 2013-06-25 and onwards only 137 model levels are available

@leiyangleon can you update the download API to handle the change internally; might have an impact on the constants for the model levels prior to 2013-06-25.
@jlmaurer once the model is loaded it should be agnostic to this difference. Let me know if that is not true.

**Comment by leiyangleon** [comment]
@dbekaert sure, looking into it.

**Comment by dbekaert** [comment]
@leiyangleon the mapping of the coefficients for 91 model levels can be found here:
https://www.ecmwf.int/en/forecasts/documentation-and-support/91-model-levels

**Comment by leiyangleon** [comment]
@dbekaert it is fount to be 2013-06-26 not 2013-06-25. I have fixed that and run a 10-year (09-20) test to verify. It works properly now.

**Comment by dbekaert** [comment]
Ok i did the test now. ERA5 and HRES multi-parallel works over the complete period.
