### ISSUE TITLE
Adding support for GMAO pre-2017-12-01 (not compatible with opendap)

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#189]
This is an extension of #36. Opendap does not support a file format change for GMAO products introduced in 2017, this means that all data prior to 2017-12-01 is not accessible with opendap, although the archive starts in Feb 20 2014.

I am not clear as to what changed in the product. I found the files to look the same when opening in panoply. 

Suggest we implement an alternative download that fetches these files using a prefixed html link.
We can construct this based on the URL for the year, month and day of month, follwed by the files we need.

For example url: https://portal.nccs.nasa.gov/datashare/gmao/geos-fp/das/Y2016/M01/D01/ has the following files:

```
  | GEOS.fp.asm.inst3_3d_asm_Np.20160101_0000.V01.nc4 | 01-Jan-2016 05:54 | 443M |  
  | GEOS.fp.asm.inst3_3d_asm_Np.20160101_0300.V01.nc4 | 01-Jan-2016 05:54 | 439M |  
  | GEOS.fp.asm.inst3_3d_asm_Np.20160101_0600.V01.nc4 | 01-Jan-2016 09:59 | 439M |  
  | GEOS.fp.asm.inst3_3d_asm_Np.20160101_0900.V01.nc4 | 01-Jan-2016 09:59 | 441M |  
  | GEOS.fp.asm.inst3_3d_asm_Np.20160101_1200.V01.nc4 | 01-Jan-2016 16:58 | 439M |  
  | GEOS.fp.asm.inst3_3d_asm_Np.20160101_1500.V01.nc4 | 01-Jan-2016 16:58 | 439M |  
  | GEOS.fp.asm.inst3_3d_asm_Np.20160101_1800.V01.nc4 | 01-Jan-2016 22:06 | 440M |  
  | GEOS.fp.asm.inst3_3d_asm_Np.20160101_2100.V01.nc4 | 01-Jan-2016 22:06 | 438M |  
  | GEOS.fp.asm.inst3_3d_asm_Nv.20160101_0000.V01.nc4 | 01-Jan-2016 05:54 | 814M |  
  | GEOS.fp.asm.inst3_3d_asm_Nv.20160101_0300.V01.nc4 | 01-Jan-2016 05:54 | 810M |  
  | GEOS.fp.asm.inst3_3d_asm_Nv.20160101_0600.V01.nc4 | 01-Jan-2016 09:59 | 808M |  
  | GEOS.fp.asm.inst3_3d_asm_Nv.20160101_0900.V01.nc4 | 01-Jan-2016 09:59 | 812M |  
  | GEOS.fp.asm.inst3_3d_asm_Nv.20160101_1200.V01.nc4 | 01-Jan-2016 16:59 | 809M |  
  | GEOS.fp.asm.inst3_3d_asm_Nv.20160101_1500.V01.nc4 | 01-Jan-2016 16:59 | 809M |  
  | GEOS.fp.asm.inst3_3d_asm_Nv.20160101_1800.V01.nc4 | 01-Jan-2016 22:06 | 812M |  
  | GEOS.fp.asm.inst3_3d_asm_Nv.20160101_2100.V01.nc4 | 01-Jan-2016 22:06 | 809M |  
```

**Comment by dbekaert** [comment]
This is being developped under https://github.com/dbekaert/RAiDER/compare/dl_historic_gmao

**Comment by bbuzz31** [comment]
This is now implemented in https://github.com/dbekaert/RAiDER/pull/194. It was tested by computing delays on 03/01/2019 using both pydap and direct download. The results were identical. Further testing is welcome.
