### ISSUE TITLE
When calling geo2rdr, line-of-sight vectors returned have larger y-values than z-values, possible reference frame issue?

### ISSUE THREAD

**Issue by jlmaurer** [dbekaert/RAiDER#19]
See https://github.com/dbekaert/RAiDER/blob/1bef6a5f1eaf41d87195ffc6eb891f21d57f4621/tools/RAiDER/losreader.py#L83

--> example lat/lon/z:  38.6/-79.4/-100 on UTC20200103T23:00:00

results in: (los_x, los_y, los_z): 
(array([[0.24365994]]), array([[0.96936308]]), array([[0.03106531]]))

@piyushrpt could this be an issue with reference frame? Orbits are fixed earth, but line-of-sight reference frame is not specified that I could find.

**Comment by dbekaert** [comment]
@jlmaurer what is the z-value here? Z geoid, Z geometric, Z? and what are the units?

**Comment by jlmaurer** [comment]
@dbekaert Z is geometric z in units of meters

**Comment by dbekaert** [comment]
@jlmaurer I looked back to some of the earlier commits from Heresh. You can find them here:
https://github.com/dbekaert/RAiDER/commits?author=hfattahi

Based on earlier commits from Heresh, i see he had a test included for the geo2rdr code: https://github.com/dbekaert/RAiDER/commit/40e8b5dda3573aa558f34389dd36993a77b1eb7f

Some observations from this test:
1. Radians are required!
2. the step-size allows you to do a grid of lon lat based on height. So in case the model has a regular lon-lat grid this could be used?

There was also a past commit to define the orientation of the look vector: https://github.com/dbekaert/RAiDER/commit/b27a99c9ad7c96453072b711ab07a917190e44d8
1. Perhaps verify what is assumed in the current code and document it. We can make changes as needed based on this.

**Comment by jlmaurer** [comment]
@dbekaert can you send me this file: 
/u/k-data/fattahi/Kurdistan/174/master/IW1.xml
so I can run the Geo2rdr test?

**Comment by dbekaert** [comment]
send them your way

**Comment by dbekaert** [comment]
close via #25
