### ISSUE TITLE
Modify pyproj calls for consistency

### ISSUE THREAD

**Issue by piyushrpt** [dbekaert/RAiDER#22]
pyproj has started respecting the order of axes for different CRS. EPSG:4326 is lat/lon now and not lon/lat like it was before.

To keep traditional behavior, add 
```
always_xy=True
```
to all calls of pyproj.transform. This might also be  causing issues that you recently encountered.

**Comment by dbekaert** [comment]
Thanks for pointing this out @piyushrpt. closed through #25
