### ISSUE TITLE
HRES intermediate solution

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#238]
To make progress in HRES calculation for GNSS we will divide the earth into multiple segments that can be loaded in memory.

_[x] - @jlmaurer: Update the loading module to read based on bbox only.
[x] - @jlmaurer: Load HRES file into RAIDER to compute delays; use the gridding option to determine allowable chunk size.
[x] @sssangha: Based on chunk size split the GNSS "global list" into different segments. Verify if the unique (union) of all the "split station files" has the same number of stations as the original "world file"_

[in progress] - @dbekaert  Compute for each "individual station file" the RAiDER delays.
[x] - @jlmaurer/ @dbekaert  Have a small program that takes the union of all the csv files per intermediate files. Verify is this program can be modified to run union of intermediate files and then union of regions; followed by intersection of the GNSS file

**Comment by dbekaert** [comment]
@sssangha @jlmaurer i updated the comment above on the progress. First two items were closed under #239

**Comment by sssangha** [comment]
@dbekaert @jlmaurer within the attached zip file are 4 files corresponding to the 4 zones within which I split up the global list of stations.

I decided to decimate by longitude, i.e. split -180 to 180 longitude into 4 long strips. The distribution between the four files is more-or-less consistent -- aside for "zone D" corresponding to Lon 90-180, which is relatively sparse.

Please let me know if you have any questions/concerns.


[split_zones.zip](https://github.com/dbekaert/RAiDER/files/5872435/split_zones.zip)

**Comment by dbekaert** [comment]
See issue related in #241 and #242

**Comment by dbekaert** [comment]
@sssangha i confirm this is working with he provided chunksizes.

**Comment by dbekaert** [comment]
@sssangha @jlmaurer im adding issue #251 to this as it would impact how fast we can make progress with our intermediate solution.

**Comment by jlmaurer** [comment]
I think this can be closed now.
