### ISSUE TITLE
Circle-CI set-up

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#24]
1.	Getting started: https://circleci.com/docs/2.0/getting-started/
2.	Starting from basics: 
a.	https://circleci.com/docs/2.0/first-steps/
b.	https://circleci.com/docs/2.0/hello-world/
3.	Getting started with real projects 
a.	Pick a good docker image – ubuntu:bionic (18.04) 
b.	Bake anaconda into it and install requirements (https://stackoverflow.com/questions/58243255/circleci-testing-with-specific-miniconda-python-and-numpy-versions
c.	Add steps to then build your software and run tests
d.	For reference, see isce config.yml - https://github.com/isce-framework/isce2/blob/master/.circleci/config.yml
i.	This uses an ARIA base image so ignore that and use ubuntu
ii.	The jobs named “test” is the only one of interest. The other ones are for automatically building docker images for ARIA on merge of PRs and on new releases – not needed yet
iii.	Isce2 config.yml should be self explanatory hopefully

**Comment by dbekaert** [comment]
@leiyangleon tracking here for circle-CI

**Comment by dbekaert** [comment]
@leiyangleon merged the PR. You might need to update the circle CI to point to this repository. I think currently will be pointing to yours.

**Comment by leiyangleon** [comment]
@dbekaert I have tested the two commands in CircleCI and found the following two error messages. Could you please take a look? 

`Starting to run the weather model calculation`
`Time type: <class 'datetime.datetime'>`
`Time: 20200103`
`Flag type is bounding_box`
`DEM/height type is "download"`
`Beginning weather model pre-processing`
`Download-only is False`
`Storing weather model at: weather_files/ERA-5_2020_01_03_T23_00_00.nc`
`Weather model ERA-5 is available from 1950-01-01 00:00:00-Present`
`ERROR: Unable to download weather data`
`Exception encountered: Missing/incomplete configuration file: /root/.cdsapirc`
`Starting to run the weather model calculation`
`Time type: <class 'datetime.datetime'>`
`Time: 20200103`
`Flag type is bounding_box`
`DEM/height type is "lvs"`
`Beginning weather model pre-processing`
`Download-only is False`
`Storing weather model at: weather_files/ERA-5_2020_01_03_T23_00_00.nc`
`Weather model ERA-5 is available from 1950-01-01 00:00:00-Present`
`ERROR: Unable to download weather data`
`Exception encountered: Missing/incomplete configuration file: /root/.cdsapirc`

**Comment by jlmaurer** [comment]
This issue occurs because a named user with credentials is required to download from the CDS API. @dbekaert Perhaps we should create a dummy user and use that for testing credentials? Or we keep a file on hand for testing purposes?

**Comment by dbekaert** [comment]
@leiyangleon see the first few lines under: https://github.com/dbekaert/RAiDER-docs
To download data you need to have a user-account.
For the testing suite we likely also need to get the downlaod API working and linked to a user account to download data. 
Perhaps we should make a dummy download account for the weather models specifically for raider testing. In that way we avoid using personal accounts.

@jlmaurer can you confirm?

**Comment by dbekaert** [comment]
> This issue occurs because a named user with credentials is required to download from the CDS API. @dbekaert Perhaps we should create a dummy user and use that for testing credentials? Or we keep a file on hand for testing purposes?

agreed.

**Comment by leiyangleon** [comment]
@dbekaert @jlmaurer _**After creating a dummy user account, the two commands successfully ran through the end. Please see below the screen output.**_

> 
Starting to run the weather model calculation
Time type: <class 'datetime.datetime'>
Time: 20200103
Flag type is bounding_box
DEM/height type is "download"
Beginning weather model pre-processing
Download-only is False
Storing weather model at: weather_files/ERA-5_2020_01_03_T23_00_00.nc
Weather model ERA-5 is available from 1950-01-01 00:00:00-Present
{'product_type': 'reanalysis', 'pressure_level': 'all', 'levtype': 'pl', 'variable': ['geopotential', 'relative_humidity', 'specific_humidity', 'temperature'], 'stream': 'oper', 'type': 'an', 'year': '2020', 'month': '1', 'day': '3', 'time': '23:00', 'step': '0', 'area': [40.4, -79.4, 38.6, -77.6], 'format': 'netcdf'}
/root/miniconda/envs/RAiDER/lib/python3.8/site-packages/urllib3/connectionpool.py:979: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cds.climate.copernicus.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2020-04-21 19:33:04,840 INFO Welcome to the CDS
2020-04-21 19:33:04,840 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-pressure-levels
/root/miniconda/envs/RAiDER/lib/python3.8/site-packages/urllib3/connectionpool.py:979: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cds.climate.copernicus.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2020-04-21 19:33:05,247 INFO Request is completed
2020-04-21 19:33:05,247 INFO Downloading http://136.156.132.110/cache-compute-0001/cache/data9/adaptor.mars.internal-1587167640.6250787-19154-1-ab3d092b-d8a1-4232-8ebe-3fd75f9f6153.nc to weather_files/ERA-5_2020_01_03_T23_00_00.nc (20.8K)

2020-04-21 19:33:05,480 INFO Download rate 89.3K/s
/root/miniconda/envs/RAiDER/lib/python3.8/site-packages/urllib3/connectionpool.py:979: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cds.climate.copernicus.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Number of weather model nodes: 1862
Shape of weather model: (7, 7, 38)
Bounds of the weather model: 38.599998474121094/40.099998474121094/-79.4000015258789/-77.9000015258789 (SNWE)
Weather model: ERA-5
Mean value of the wet refractivity: 18.97490354587961
Mean value of the hydrostatic refractivity: 125.28719173379606
Saving weather model object to pickle file
Weather Model Name: ERA-5

======Weather Model class object=====
Number of points in Lon/Lat = 7/7
Total number of grid points (3D): 1862
Latitude resolution: 0.2
Longitude resolution: 0.2
Native projection: epsg:4326
ZMIN: -100
ZMAX: 15000
Minimum/Maximum y:  38.60/ 40.10
Minimum/Maximum x: -79.40/-77.90
Minimum/Maximum zs/heights:    -100.00/  46068.34

k1 = 0.776
k2 = 0.233
k3 = 3750.0
Humidity type = q

Class name: ea
Dataset: era5

A: [0.0, 2.000365, 3.102241, 4.666084, 6.827977, 9.746966, 13.605424, 18.608931, 24.985718, 32.98571, 42.879242, 54.955463, 69.520576, 86.895882, 107.415741, 131.425507, 159.279404, 191.338562, 227.968948, 269.539581, 316.420746, 368.982361, 427.592499, 492.616028, 564.413452, 643.339905, 729.744141, 823.967834, 926.34491, 1037.201172, 1156.853638, 1285.610352, 1423.770142, 1571.622925, 1729.448975, 1897.519287, 2076.095947, 2265.431641, 2465.770508, 2677.348145, 2900.391357, 3135.119385, 3381.743652, 3640.468262, 3911.490479, 4194.930664, 4490.817383, 4799.149414, 5119.89502, 5452.990723, 5798.344727, 6156.074219, 6526.946777, 6911.870605, 7311.869141, 7727.412109, 8159.354004, 8608.525391, 9076.400391, 9562.682617, 10065.978516, 10584.631836, 11116.662109, 11660.067383, 12211.547852, 12766.873047, 13324.668945, 13881.331055, 14432.139648, 14975.615234, 15508.256836, 16026.115234, 16527.322266, 17008.789063, 17467.613281, 17901.621094, 18308.433594, 18685.71875, 19031.289063, 19343.511719, 19620.042969, 19859.390625, 20059.931641, 20219.664063, 20337.863281, 20412.308594, 20442.078125, 20425.71875, 20361.816406, 20249.511719, 20087.085938, 19874.025391, 19608.572266, 19290.226563, 18917.460938, 18489.707031, 18006.925781, 17471.839844, 16888.6875, 16262.046875, 15596.695313, 14898.453125, 14173.324219, 13427.769531, 12668.257813, 11901.339844, 11133.304688, 10370.175781, 9617.515625, 8880.453125, 8163.375, 7470.34375, 6804.421875, 6168.53125, 5564.382813, 4993.796875, 4457.375, 3955.960938, 3489.234375, 3057.265625, 2659.140625, 2294.242188, 1961.5, 1659.476563, 1387.546875, 1143.25, 926.507813, 734.992188, 568.0625, 424.414063, 302.476563, 202.484375, 122.101563, 62.78125, 22.835938, 3.757813, 0.0, 0.0]
B: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7e-06, 2.4e-05, 5.9e-05, 0.000112, 0.000199, 0.00034, 0.000562, 0.00089, 0.001353, 0.001992, 0.002857, 0.003971, 0.005378, 0.007133, 0.009261, 0.011806, 0.014816, 0.018318, 0.022355, 0.026964, 0.032176, 0.038026, 0.044548, 0.051773, 0.059728, 0.068448, 0.077958, 0.088286, 0.099462, 0.111505, 0.124448, 0.138313, 0.153125, 0.16891, 0.185689, 0.203491, 0.222333, 0.242244, 0.263242, 0.285354, 0.308598, 0.332939, 0.358254, 0.384363, 0.411125, 0.438391, 0.466003, 0.4938, 0.521619, 0.549301, 0.576692, 0.603648, 0.630036, 0.655736, 0.680643, 0.704669, 0.727739, 0.749797, 0.770798, 0.790717, 0.809536, 0.827256, 0.843881, 0.859432, 0.873929, 0.887408, 0.8999, 0.911448, 0.922096, 0.931881, 0.94086, 0.949064, 0.95655, 0.963352, 0.969513, 0.975078, 0.980072, 0.984542, 0.9885, 0.991984, 0.995003, 0.99763, 1.0]

Getting the DEM
Beginning DEM download and warping
DEM download finished
Beginning interpolation
Interpolation finished
Saving DEM to disk
Beginning delay calculation
Reference z-value (max z for integration) is . m
Number of processors to use: 1
/root/miniconda/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delay.py:107: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  zs_wm = f['z'].value.copy()
/root/miniconda/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delay.py:108: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  total_wet=f['wet_total'].value.copy()
/root/miniconda/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delay.py:109: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  total_hydro=f['hydro_total'].value.copy()
Delays have been written to the weather model file; see weather_files/ERA5_2020-01-03 23:00:00_39.0N_40.0N_-79.0E_-78.0E.h5
Starting to run the weather model calculation
Time type: <class 'datetime.datetime'>
Time: 20200103
Flag type is bounding_box
DEM/height type is "lvs"
Beginning weather model pre-processing
Download-only is False
Weather model already exists, please remove it ("weather_files/ERA5_2020-01-03 23:00:00_39.0N_40.0N_-79.0E_-78.0E.h5") if you want to create a new one.
Beginning delay calculation
Reference z-value (max z for integration) is . m
Number of processors to use: 1
/root/miniconda/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delay.py:107: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  zs_wm = f['z'].value.copy()
/root/miniconda/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delay.py:108: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  total_wet=f['wet_total'].value.copy()
/root/miniconda/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delay.py:109: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  total_hydro=f['hydro_total'].value.copy()
Finished writing data to ./ERA5_delays_2020-01-03T23:00:00_std.hdf5
>
