### ISSUE TITLE
Updates to raiderDelay.py argparse

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#26]
##Update for user-friendliness needed in argparse:

1. Provide example for each input. E.g. ISO 8601 format not clear to all users. (e.g. multiple variants for parsing day and time exist online, clarify with e.g. YYYMMDD)
2. Specify to which reference the DEM and reference the height levels are. i.e. ellipsoid, geoid and  corrected for ellipsoid etc
3. The options used to be a bit more nested. i.e. LOS or statevector or zenith; there is no mention anymore of zenith option. Correct in argparse visualization
4. The options used to be a bit more nested: i.e. DEM or levels. Correct in argparse visualization
5. Unclear what the pickle file option is, lacks description and might be only relevant for testing.  
6. If the parallel option does not work, comment it out.
7. Also add which models and how to specify them. e.g. its caps sensitive. 
   For now only list the once work itself.
8. im not sure if –modelBBOX is the right word. Rather see it as a region bbox, where internally the model bbox is extended such interpolation works. 
9. Add in multiple run example
- Zenith for ERA5 at model grid nodes at topo
- Zenith for ERA5 at model grid nodes at fixed height level
- los for ERA 5 using Sentinel-1 orbit at model grid nodes at topo
- los for ERA 5 using ISCE los file at model grid nodes at topo

**Comment by dbekaert** [comment]
PR is incorporated.

Syntax does not yet fully capture the options correctly:

Its LOS or SV; and if not specific it will be zenith.
Is there a way to cluster these inputs togehter to show they are nested?
Ray has them more nested before and did not list them all as individual options.

- no need to mix DEM with lon lat information or weatehr model grid nodes

- area or bbox. Which takes precedent. Rather remove information on the bbox of which teh model is being download. make it area over which delays are calculated.

**Comment by sssangha** [comment]
@dbekaert to add to this, I would suggest to make the "outformat" and "model" input arguments not case-sensitive. E.g. the code should be able to handle cases where the user specifies "ERA5" or "era5".

Also, maybe adding a synopsis of each major function's operation (as we do in ARIA-tools) would be a good idea.

**Comment by dbekaert** [comment]
@jlmaurer you mentioned to found a solution?
