### ISSUE TITLE
NCUM model filename issue

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#270]
See attached screenshot for the reported error by @kam3545 

![Screenshot from 2021-03-01 11-39-46](https://user-images.githubusercontent.com/19240905/109523158-e35ff600-7a63-11eb-86ed-7b57652917e0.png)

**Comment by dbekaert** [comment]
@leiyangleon Could you look into this one while we add unit test for all models in scenario 1?

**Comment by leiyangleon** [comment]
The issue should be fixed by this PR #281.

**Comment by dbekaert** [comment]
Thanks @leiyangleon.
@kam3545 can you give it a try?
