### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kam3545** [dbekaert/RAiDER#287]
**Describe the bug**
Issue in **Compute Zenith delays using a GNSS station list**

**To Reproduce**
1. Command used
**raiderDelay.py --date 20180701 --time 00:00:00 --station_file data/xx.csv --model ERA5**
[xx.csv.gz](https://github.com/dbekaert/RAiDER/files/6113575/xx.csv.gz)

2. Error Output
Image attached

**Expected behavior**
This command working fine when downloaded data for same region online.
But, produce ValueError when implemented for global model file. In this case, length of values are mismatch as shown in attached figure. 

**Screenshots**
attached 
![Screenshot from 2021-03-09 13-35-48](https://user-images.githubusercontent.com/41619377/110583773-34729700-8194-11eb-86fd-bbe8b33327fc.png)

**Comment by kam3545** [comment]
@dbekaert please see above issue.

**Comment by dbekaert** [comment]
@jlmaurer could you try to replicate this issue?
