### ISSUE TITLE
[BUG] second example command (by running the helper command) failed for HRES after one execution

### ISSUE THREAD

**Issue by leiyangleon** [dbekaert/RAiDER#289]
**Describe the bug**

The second helper command runs well except the reported bug in #273. However, at the 2nd trial of the same command after running it once, the program failed. The problem does not affect other weather models, i.e. only HRES is affected.

**To Reproduce**

1. Command used
`raiderDelay.py --date 20200103 --time 23:00:00 -b 39 40 -79 -78 --model HRES --zref 15000 --heightlvs 0 100 200 -v
`
2. Error Output (2nd time running the above command)
`WARNING: Weather model already exists, please remove it ("['./weather_files/HRES_2020_01_03_T23_00_00.nc']") if you want to download a new one.`
`Extent of the input lats/lons is: [39.0, 40.0, -79.0, -78.0]`
`Extent of the weather model is: [<xarray.DataArray 'latitude' ()>`
`array(38.83784, dtype=float32), <xarray.DataArray 'latitude' ()>`
`array(40.135136, dtype=float32), <xarray.DataArray 'longitude' ()>`
`array(280.83783, dtype=float32), <xarray.DataArray 'longitude' ()>`
`array(282.13513, dtype=float32)]`
`ERROR: The weather model passed does not cover all of the input points; you need to download a larger area.`
`ERROR: Date 2020-01-03 23:00:00 failed`
`Traceback (most recent call last):`
`  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/runProgram.py", line 208, in _tropo_delay`
`    (_, _) = tropo_delay(args_copy)`
`  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/delay.py", line 121, in tropo_delay`
`    makePlots=True`
`  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/processWM.py", line 79, in prepareWeatherModel`
`    'The weather model passed does not cover all of the input '`
`RuntimeError: The weather model passed does not cover all of the input points; you need to download a larger area.`

**Comment by jlmaurer** [comment]
Note: only for HRES, other models are fine.

**Comment by leiyangleon** [comment]
closing this as it has been solved by PR #285.
