### ISSUE TITLE
[BUG] Heights are not currently being consistently handled throughout the code

### ISSUE THREAD

**Issue by jlmaurer** [dbekaert/RAiDER#293]
- There are ellipsoidal and geoidal heights currently being used without any conversions between
- Inputs are likely to always be ellipsoidal, while weather models are typically related to the geoid
- Will difference be significant enough to fix given the range of variations between the geoid and WGS-84 ellipsoid?

**Comment by jlmaurer** [comment]
Need to check what the vertical datum is for each weather model
ECMWF - EGM96

**Comment by dbekaert** [comment]
So two items here:

1) weather models come with its own native projection (horizontal proj). Both pressure and model levels compute geopotential which would be respective to the geoid. The geoid depends on what is assumed by the model.

"ECMWF data is referenced in the horizontal with respect to the WGS84 ellipse (which defines the major/minor axes) but in the vertical it is referenced to the Geoid (EGM96)." see [here](https://confluence.ecmwf.int/display/CKB/ERA-Interim%3A+documentation)

We should add in the vertical datum as well using the proj conventions that are compatible with GDAL.

gdalwarp -s_srs "+proj=longlat +datum=WGS84 +no_defs +geoidgrids=egm96_15.gtx" -t_srs "+proj=longlat +datum=WGS84 +no_def" dem_in_egm96_geoid.tif dem_in_wgs84_ellipsoid.tif

2) we convert the weather model vertical sampling into the same coordinate system as the DEM. We need to make sure that the DEM projection and vertical datum are propagated 

3) Example on converting the EGM96 to WGS84 vertical datum:
- raters with corrections [here](https://www.agisoft.com/downloads/geoids/)
- gdalwarp -s_srs "+proj=longlat +datum=WGS84 +no_defs +geoidgrids=egm96_15.gtx" -t_srs "+proj=longlat +datum=WGS84 +no_def" dem_in_egm96_geoid.tif dem_in_wgs84_ellipsoid.tif

**Comment by dbekaert** [comment]
@cmarshak could you cover this once back? This is synergistic with the ARIA work.

**Comment by cmarshak** [comment]
Ok - we can figure out what's best for this repo.

I worked with David on this for ARIA/ACCESS and it is still very much a work in progress (or maybe it will just be cut/paste for these types of issues): https://github.com/aria-jpl/dem_stitcher

There are things that can be adapted here - likely these two pieces:

read geoid directly from the link above: https://github.com/aria-jpl/dem_stitcher/blob/main/dem_stitcher/geoid.py#L19-L59
removing the geoid: https://github.com/aria-jpl/dem_stitcher/blob/main/dem_stitcher/geoid.py#L62-L92

If you want to do this from scratch for this repo, the URL data is here:

https://github.com/aria-jpl/dem_stitcher/tree/main/dem_stitcher/data (download it, unzip, and read the urls and they tell you the open location of the various tiles).

There is an annoying piece: DEMs can be georeferenced with respect to upper left corners (USGS DEMs) or the pixel center (SRTM, GLO-30) see [1] and [2].

[1] https://www.usgs.gov/core-science-systems/eros/topochange/science/srtm-ned-vertical-differencing?qt-science_center_objects=0#qt-science_center_objects
[2] https://github.com/OSGeo/gdal/issues/1505#issuecomment-489469904

**Comment by jlmaurer** [comment]
Here's the code line where the DEM gets downloaded: 
https://github.com/dbekaert/RAiDER/blob/66de8814d0ba010f6c3378bf7bb8a8a1f64e5edc/tools/RAiDER/dem.py#L255

Note that it gets chunked if needed.

**Comment by jlmaurer** [comment]
#318 addresses the DEM aspect of this and puts everything in WGS-84 ellipsoidal. Need to add vertical datums to weather model class definitions and convert those to the ellipsoid.

**Comment by dbekaert** [comment]
@jlmaurer Can you track the projection and vertical datum in each of the weather models, and add a note here for reference of @cmarshak how he can access it within the code. 

@cmarshak Can you based on the model vertical datum add in a correction for it to bring the vertical datums in sync with the DEM?

**Comment by jlmaurer** [comment]
This is resolved in [Discussion 501](https://github.com/dbekaert/RAiDER/discussions/501)
