### ISSUE TITLE
Documentation for adding new weather models

### ISSUE THREAD

**Issue by jlmaurer** [dbekaert/RAiDER#3]

**Comment by dbekaert** [comment]
@jlmaurer Can we capture in a Juypter Notebook the changes that needs to be made to add in a new weather model? 

1) data download?
2) the model class?
3) where in the code do users need to make changes?
- e.g. argparse, some checks in the code.

Suggest to do this while we add in ERA5T, MERRA-2, GMAO etc.
Note that notebooks are to be stored into the RAiDER-docs folder.
