### ISSUE TITLE
Need to handle left-looking LOS

### ISSUE THREAD

**Issue by jlmaurer** [dbekaert/RAiDER#310]
Code reference:
https://github.com/dbekaert/RAiDER/blob/3dca5aa8de0a1750cc5aac410c00e5446d38c718/tools/RAiDER/losreader.py#L253

Currently no explicit handling of left-looking sensors; incidence angle would need to be negative?

**Comment by dbekaert** [comment]
NISAR is a left looking instrument. We should circle back to this and address it.

**Comment by jlmaurer** [comment]
This shouldn't be an issue, according to Heresh. The only part of the code this would affect is calculating unit look vectors from heading and incidence angle, and the heading should account for the look direction. Thus the existing code should work fine. The other part of the code uses the satellite state vectors and should also work fine.
