### ISSUE TITLE
Update HRRR weather model archive location to new NOAA AWS API

### ISSUE THREAD

**Issue by jlmaurer** [dbekaert/RAiDER#324]
The HRRR weather model has (finally!) started to be [archived by NOAA](https://registry.opendata.aws/noaa-hrrr-pds/).[ Here's a link](https://home.chpc.utah.edu/~u0553130/Brian_Blaylock/hrrr_FAQ.html) to the original University of Utah repository with the explanation of the new data systems. NOAA is storing the GRIB files on AWS, while Brian Baylock's group at UU is storing them as [ZARR files](https://zarr.readthedocs.io/en/stable/). However, [according to their description of this dataset](https://mesowest.utah.edu/html/hrrr/zarr_documentation/) it sounds like they won't be storing all of the available data, so probably we simply need to switch to the NOAA AWS archive. I think file I/O should be pretty similar to what it is now.

NOAA has a readme on accessing the data on S3 on Github: https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-hrrr

**Comment by dbekaert** [comment]
addressed in PR #379
