### ISSUE TITLE
[BUG] Downloaded Weather Model (.nc) is not consistent with the bounding box

### ISSUE THREAD

**Issue by ngohikennyyue** [dbekaert/RAiDER#355]
**Describe the bug**
I have multiple occasion that I download the weather model (WM) using `raiderDelay.py` with a bounding box or GPS station parameter. It does not have problem throughout the download process. However, when I need to extract values from multiple dates in the AOI, there are some mismatching in the shape (WM grid nodes). x and y dimension is not consistent. z level is consistent with 38 levels but the level may not be the same for all the days I downloaded. I plot every 30 days of the WM and AOI for reference for such mismatching behavior and WM download with list of GPS stations.

**To Reproduce**
`raiderDelay.py --date 20170101 20191231 --time 23:00:00 -b 39 42 -81 -76 --model ERA5 --out Projects/InSAR/weather_file/ -v`

`!raiderDelay.py --date 20151029 20151112 --time 16:00:00  --station_file GNSS/Hawaii/Special_time/gnssStationList_overbbox.csv --model ERA5 --out GNSS/Hawaii/Special_time/GPS_station_delay -w GNSS/Hawaii/Special_time/weather_files --verbose`

**Expected behavior**
It is expected to have the weather model downloaded where-ever it's specified within a bounding box or list of GPS stations.

![Penn_RAiDER_Bbox (1)](https://user-images.githubusercontent.com/55525882/177915068-064a2bdc-a0e0-40fe-9de7-aa077218f2e2.png)
<img width="1031" alt="Screen Shot 2022-07-07 at 11 27 46 PM" src="https://user-images.githubusercontent.com/55525882/177916924-0cd6e1cb-23d8-4021-aeb5-5723aad6c4ce.png">

**Desktop (please complete the following information):**
 - RAiDER git tag: raiderDelay.py --bbox   and --station_file
 - OS - Run on conda env with jupyter notebook and and foundry. 

**Additional context**
I have not plot the difference in z-levels. I have only done some inspection by printing out all the z-levels and compare. I could include them in here later.

**Comment by dbekaert** [comment]
@bbuzz31 @jlmaurer i believe this has been resolved. Please confirm

**Comment by bbuzz31** [comment]
I think this is okay now:

![image](https://user-images.githubusercontent.com/15522503/211438058-a831f9d6-eee0-4da4-a1d2-6ff248cb647c.png)

yaml:
```
aoi_group:
  bounding_box: 39 42 -81 -76

date_group:
  date_list: (20170101, 20170131)

look_dir: right
los_group: {}
runtime_group:
  output_directory: .
  raster_format: nc
time_group:
  time: '23:00:00'
weather_model: ERA5
```
