### ISSUE TITLE
Fixing Zentith delay for all variants (point, grid, cube)

### ISSUE THREAD

**Issue by jlmaurer** [dbekaert/RAiDER#37]

**Comment by jlmaurer** [comment]
*Update*: Minimal working code should be able to compute zenith delays for the following inputs: 
- lat/lon file specified
- station list specified
- bounding box specified
- each of the above options with fixed height levels specified

**Comment by jlmaurer** [comment]
Hey @dbekaert @Askaholic @leiyangleon I have a question. The current HEAD breaks when passing the --station_files option because of the following line: 
https://github.com/dbekaert/RAiDER/blob/eadc4627632dfcd76f2bd4f3c33de380e1cf0921/tools/RAiDER/delayFcns.py#L167

## Apparent Problem
The problem here is that the input data can be a 1-D list of stations, a 2-D raster, or a 3-D data cube (e.g. weather model nodes). Ideally we would like a single function that is agnostic of the input data shape, but right now the code assumes a 2D raster.

## Underlying problem
The real problem here is that we read the input data from an HDF5 file by chunk, and if the data dimension changes then the chunk size dimension also changes. Because of Python's GIL, we have to pass the HDF5 file pointers to each one of the subprocesses like so: 
https://github.com/dbekaert/RAiDER/blob/eadc4627632dfcd76f2bd4f3c33de380e1cf0921/tools/RAiDER/delayFcns.py#L157
where SP and SLV are the relevant HDF5 arrays. This is good because the data only gets read into memory as chunks, but bad because that means the function (unpacking_hdf5_read) doesn't know what the shape of the chunk is, and so has to do different things based on different size chunks. Currently this is not done so the code breaks. 

## Possible solutions
- One option is to leave the code as is but add in flags for various chunk sizes. I've implemented this in one of my branches and it seems to work, but the code is messy
- One option would be to flatten all the input data before writing to the HDF5 file, then perform chunking on the resulting 1D array. This isn't great if anyone needs to access the intermediate HDF5 data, but would make the delay calculation input-size agnostic
- Other ideas? 

I'm posting to this issue because currently the code doesn't pass the "minimal working example" in the comment [above](https://github.com/dbekaert/RAiDER/issues/37#issuecomment-645085885). If you guys have ideas about what is best please share!

**Comment by dbekaert** [comment]
Independent of the 1-2-3D chunk issue. I do not think we should  have variable chunk-size based on the number of cores available (https://github.com/dbekaert/RAiDER/blob/eadc4627632dfcd76f2bd4f3c33de380e1cf0921/tools/RAiDER/delayFcns.py#L93), rather have the chunk-size set based on what the maximum computational need/ memory would be for a chunk. This would make the code much more agile when we process large regions. 

From what i recall when implementing chunking for GIaNT:
- The chunking process becomes more effective if they are of size 2^n. However i could not directly find that documentation online. Perhaps @leiyangleon has some thoughts?
https://support.hdfgroup.org/HDF5/doc/Advanced/Chunking/
- I also noticed that I wrote two intermediate hdf5 files to which i applied chunking when saving them. The subsequent calculations i did combining both files where done over exactly the same chunk sizes. If the chunk size upon creation was not the same as i was looping over, it was much more inefficient.

**Comment by leiyangleon** [comment]
@dbekaert @jlmaurer 
1. I can see the current chunking restricts the extension of data dimensions. I remember the original delayFcns.py @jlmaurer wrote has chunks included from the weather model file but somehow @jlmaurer decided to remove it and switched to the no-chunk version. So I started from the no-chunk version with makepoints1D, and then split the 1-D array to several segments (what I call `chunks`) for parallel reading purposes. If it is hard to extend to 2-D or 3-D, it might be helpful to 1) ignore my parallel version, 2) go back to the 1-D version of @jlmaurer and add chunks back, and 3) directly extend that from 1-D to 2-D and 3-D. Then I can probably help to parallelize the code.

2. @dbekaert for the number of chunks (segments added by me NOT the native chunks in the weather model file), please see my previous NISAR weekly reports for the tabulated comparison of runtime vs. # of processes (my chunks). It was found that when # of processes = # of cores, it is optimal. This of course does not take into account of the native chunks in the weather model file as I was only using the no-chunk version of delayFcns.py. 
BTW, you might get confused by the parameter `cpu_num` which represents # of processes (not # of cores) and is adjustable as the user specified. See the following line for `def get_delays` where `cpu_num` is an input parameter given by the users not a fixed number of cpu count (only when users don't specify, we use cpu count for default which is more or less optimal based on my previous runtime tests).
https://github.com/dbekaert/RAiDER/blob/eadc4627632dfcd76f2bd4f3c33de380e1cf0921/tools/RAiDER/delayFcns.py#L67 
Anyway, taking into account of the native chunks of weather mode file with the 2-D/3-D extension, it would be much better to add the chunk and do the extension first as I suggested above, and then we will go from there to parallelize it.

**Comment by jlmaurer** [comment]
@leiyangleon @dbekaert I think that setting the number of processes to the number of cores probably is optimal for small (small meaning <amount of available RAM) data sets because it minimizes the amount of overhead required when doing passing back and forth from processes. Possibly once the chunk size exceeds the amount of available RAM then it becomes more efficient to have more chunks.

**Comment by dbekaert** [comment]
At this point the work by @leiyangleon is already an improvement where we were in the past, so would want to see where we can enhance it more.

@leiyangleon  @jlmaurer, perhaps lets have a meeting when @Askaholic is done with profiling to see where bottleneck slow-down is occuring?
