### ISSUE TITLE
[BUG] Option for NaN Checks

### ISSUE THREAD

**Issue by piyushrpt** [dbekaert/RAiDER#382]
**Describe the bug**
- Add an option to ensure that none of the computations result in NaNs
- This is primarily meant for production to prevent results with NaNs being shipped
- If a NaN is encountered, raise an error to let user know that sufficient padding has not been provided for weather model or possibly wrong inputs such as the orbit file has been provided.

**Comment by dbekaert** [comment]
@jlmaurer is working on this under #475.
