### ISSUE TITLE
Add ERA5T model to RAiDER

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#39]
Adding this here to track it as part of the millstone.
Has been added already, but should be verified.

**Comment by dbekaert** [comment]
A version was merged into RAiDER under  #34. 

@jlmaurer Can you update the status of this ticket.
- Still in need for some work to be done?
- Was the syntax of the code updated on how one can leverage this model?

**Comment by jlmaurer** [comment]
I'm closing this issue as ERA5T has been added and verified.
