### ISSUE TITLE
Question about multiple orbit files

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#391]
For particular SLCs, could multiple orbit files be required? In the event two orbit files are needed, can the yml parser still be used?

See #381 for a sample yaml which I am using.

**Comment by piyushrpt** [comment]
It is highly unlikely that multiple orbit files will be needed for an SLC. The orbit products themselves usually have several minutes of overlap.  If this were needed to be done for some strange reason - this should reside in isce3; something similar to https://github.com/isce-framework/isce2/blob/bb4d3b545b0400a9c15e5dd7b6f1cb577f77bfa2/contrib/stack/topsStack/baselineGrid.py#L35
