### ISSUE TITLE
Docker image download issue

### ISSUE THREAD

**Issue by fuklokchan** [dbekaert/RAiDER#393]
When I try the suggested command:
docker pull ghcr.io/dbekaert/raider:latest

on UNIX machine with CENTOS

I got the message:
Error response from daemon: manifest unknown

**Comment by jhkennedy** [comment]
@fuklokchan this is currently expected. The convention typically used for docker tags is `latest` == "latest stable release". The docker build was added recently in #371, and there hasn't been a release sense then, so there is no `latest` tag. 

You can grab the `test` tag, which is built off the most recent merge to develop like:
```
docker pull ghcr.io/dbekaert/raider:test
```

so by convention:
* merge to `main` branch -> `latest` tag, `v*` tag (last released version #)
* merge `develop` branch -> `test` tag

I'll leave this issue open until we do the next release, which will provide the `latest` tagged image.

**Comment by dbekaert** [comment]
This is working and documentation has been clarified
