### ISSUE TITLE
[BUG] Reuse weather model with HRRR

### ISSUE THREAD

**Issue by bbuzz31** [dbekaert/RAiDER#410]
If you give a bounding box in geo coords to HRRR it will successfully download and calculate delays.

However, if the HRRR file already exists, then the geo bounding box will be mismatched with the projected coordinates.

This is now addressed in #409 but the bounds calculated with pyproj are somehow too small.
Possibly there is a problem when we compute extents in `_makeDataCubes` (although this is written correctly to file)?

Error:
`Extent of the weather model is (xmin, ymin, xmax, ymax):-77.44, 35.50, -73.15, 38.07
Extent of the input is (xmin, ymin, xmax, ymax): -76.60, 35.40, -74.10, 38.20
ERROR: The weather model passed does not cover all of the input points; you need to download a larger area.
ERROR: Date 2018-11-13 23:00:00 failed`

**Comment by dbekaert** [comment]
Has this been tested for all models?

@jlmaurer GMAO and HRRR tested it. We should test for the  others and then close.
