### ISSUE TITLE
release notes

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#413]
RAiDER package was refactored to use a configure file (yaml) to parse parameters. In addition the package has been added to a conda distribution with automatic docker push upon new version releases. Various models were tested for consistency (others were disabled for the time being) with propagation delays computation support for zenith, slant through zenith projection using orbit file, and slant through ray-tracing using orbit file. Modules were restructured for computational performance improvement. 

This release is the initial release to the NISAR ADT for supporting the generation of the stratospheric ancillary correction using HRES model. 

### New/Updated Features:
+ Supported for models (verified): 
   - ECWMF: HRES, ERA5, and ERA5T access verified and tested
   - NASA GSFC: GMAO access fix for PYDAP changes
   - NOAA: HRRR access through AWS S3 bucket (using [Herbie](https://github.com/blaylockbk/Herbie)) and correction on incorrect loading of the pressure.
   - NCMR: not tested
   - Other models are currently disabled (MERRA-2, WRF, ERA-I)
+ Three flavors for computing propagation delays:
   - Zenith delays
   - Slant delays through projection from Zenith (supported through orbit file)
   - Slant delays through ray-tracing (supported through orbit file)
+ Refactoring and computational improvements for delay computation
   - Better organized for individual function calls
+ When using a pre-existing weather model file, raise a warning instead of an error when the existing weather model doesn't cover the entire AOI. 
+ Support for delay outputs at:
   - 2D coordinate list (x,y) for a user-defined height or at topographic height
   - 2D grid at user-specified output sampling (x,y) and coordinate projection for a user-defined height or by default at topographic height 
   - 3D cube at weather model grid notes or at user-specified output sampling (x,y,z) and coordinate projection 
+  Docker container images are provided with all the necessary dependencies pre-installed. See: https://github.com/dbekaert/RAiDER/#using-the-docker-image
+ Conda distribution support has been added 
+ CLI has changed from `raiderDelay.py` to `raider.py` with options provided through configure file (yaml format). 
+ Unit testing for slant ray-tracing
+ RAiDER-Docs documentation updated for changes in RAiDER package

### Not implemented / supported in this release:
+ Custom DEMs 
+ Pypi (`pip install` capability)
+ Slant delays without an orbit file (e.g. own 2D or 3D LOS files) 
+ GUNW product input/output
+ Complete unit test coverage
+ Detailed API documentation
+ Accessing RAiDER as a Python Library.

### Contributors
- Jeremy Maurer
- Brett Buzzanga
- Piyush Agram - _(Descartes Labs)_
- Joseph Kennedy
- Matthew Licari
- David Bekaert

**Comment by jlmaurer** [comment]
updates: 
- ERA-I is evidently not working now. Pretty sure it was running before but it's now broken, so I removed it. 
- Add features not yet implemented
- It's a bit confusing because we need to deliver install and user instructuions, but that's in the raider-docs repo. Should we reference those updates here?

**Comment by jhkennedy** [comment]
For Docker, you might instead say:

* Docker container images are provided with all the necessary dependencies pre-installed. See: https://github.com/dbekaert/RAiDER/#using-the-docker-image

**Comment by dbekaert** [comment]
above comments have been merged into the release notes. @jhkennedy We should be able to use the above once we push to main.

Last items to check off:

- [ ] CI changes for

**Comment by dbekaert** [comment]
add CI/CD is under #416
