### ISSUE TITLE
ISCE3 is overconstrained in the `environment.yml` file

### ISSUE THREAD

**Issue by jhkennedy** [dbekaert/RAiDER#425]
In #422 , due to https://github.com/conda-forge/isce3-feedstock/issues/33, ISCE3 was pinned to a specific build:
https://github.com/dbekaert/RAiDER/blob/4ecd5da332bd726f9097ff3bb4fd81405981a622/environment.yml#L25

This should be relaxed once the isce3 build is fixed.

**Comment by piyushrpt** [comment]
It should work as is. I don't see any major changes in the lower level functions.

**Comment by bbuzz31** [comment]
Fixed in #443
