### ISSUE TITLE
STATS: GNSS archive support 

### ISSUE THREAD

**Issue by jlmaurer** [dbekaert/RAiDER#44]
The stats class can be seen as a pre- and post-processor for RAiDER.
Below are a few items that we plan to incorporate in the RAiDER stats class (not within Raider code-base itself) to interact with  GNSS archives.

# Archives:
1) UNR Geodetic Laboratory 

2) JPL Measures 

# Functionality:
Ability to talk to the above GNSS provider to get station information for a given period in time that have zenith delays. 
- option 1) to only retrieve the lon lat  hgt information over the specified period in time
- option 2) to retrieve in addition the zenith delay information. over the specified period in time and the identified sampling in time

# Formatting:
We should think it through on what the format would be for this. Both options should be compatible with RAiDER as a station list. We should probably also think about the formation on what RAiDER will output such the statistical class can welcome it. This needs allignment with @leiyangleon (see ticket #48).

**Comment by dbekaert** [comment]
@jlmaurer could you provide some snippets here for @sssangha wrt data-download of UNR.
e.g. Perhaps some of the past code and the jupyter notebook you shared?

**Comment by sssangha** [comment]
To add some more specifics for Example 1: Inputs: Valid UTC time that coincides with whole 5 minute interval (e.g. 16:00 as 1600, 16:05 as 1605). Later would need to implement dummy-proof to round inputs that aren't whole 5 minutes intervals (e.g. 1604 to 1605, 1602 to 1600). 

I propose we parse GPS information virtually with vsicurl and build up record in netcdf format. @jlmaurer, to follow-up with David's question, is it possible to leverage vsicurl to access the data?

**Comment by dbekaert** [comment]
wrt buiding up a netcdf file (TBD), adding more information on CF compliance to ticket #48.

**Comment by jlmaurer** [comment]
Hey @dbekaert and @sssangha , yes I think vsicurl + vsizip would be a great way to do this. Unfortunately I seem to have lost my notebook, but I have two scripts thatcan serve as a starting point. They come with no guarantees but they are a start. downloadGNSSdelays.py can check or download delays from UNR (although it's not completely working at the moment) and getStationDelays.py shows what I had done before with the netcdf file formatting. Both codes and an executable are in the [tropo branch of my RAiDER fork](https://github.com/jlmaurer/RAiDER-1/tree/tropo) inside the gnss sub-package (see below). 

### Current Deficiencies
- no plots 
- no use of vsi*
- Currently only UNR repo
- No CF-compliance, or even any real metadata, with the netcdf part
- no parallelization of station checking, which would be almost trivial to add and speed things up quite a bit for the whole world
- no logging and not great error checking

### Format within a new sub-package?
Given the growing complexity of this it might make sense to place the gnss delay + stats-related codes into their own sub-package within RAiDER as is currently done for the weather models, so: RAiDER/tools/RAiDER/gnss. This is what I've done in the branch off my fork.

**Comment by dbekaert** [comment]
This has been closed out for now. The JPL measures i would say we wait till the next website is launched before we invest time in to.
