### ISSUE TITLE
[BUG] Incorrect CRS projection in data cube

### ISSUE THREAD

**Issue by bbuzz31** [dbekaert/RAiDER#448]
For a bounding box over LA (SNWE=28 39 -123 -112), the projection is over Taiwain ([Hu Tzu Shan 1950](https://spatialreference.org/ref/epsg/hu-tzu-shan/). Taiwan is around +123ºE so probably just a sign / wrapping error.

![image](https://user-images.githubusercontent.com/15522503/208210499-d5e368b0-9834-4cdb-8661-39cd836e76e0.png)

**Comment by piyushrpt** [comment]
Some typo in code setting `EPSG:4236` instead of `EPSG:4326`

**Comment by bbuzz31** [comment]
Found it, thanks @piyushrpt (Included in #445)
