### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#47]
Logging support to prepare the code to be ready for production like environments. 
We could adopt a similar strategy as used in ISCE2 or ISCE3, the latter being production code for NISAR.

# Internal Python logging (ISCE2) option
ISCE2 uses python’s built-in logging module, set up using the ISCE2-specific configuration file at defaults/logging/logging.conf. https://github.com/isce-framework/isce2

# Pyre Journal logging (ISCE3) option - Preferred 
Would be leveraging the `journal` module of `Pyre`. Notes by @aivazis: See https://github.com/pyre/pyre under tests/journal.lib/*_example.cc for examples of how to use the journal in c++, and tests/journal.api/*_example.py for the corresponding python. Example folder is [here](https://github.com/pyre/pyre/tree/master/tests/journal.api) 

In general, messages are logged into channels. Each channel has a severity and a name. The severity is a compile time attribute, determined by the constructor you invoke. The name is a runtime choice.

For example:
In c++
```
    #include <pyre/journal.h>
    …
    void foo() {
        …
        // make a channel
        pyre::journal::info_t channel(“isce3.geocode”);
        // say something
        channel
            << “Hello world!”
            << pyre::journal::endl(__HERE__); // the macro is provided by journal and logs source file, line, function name
```

or for Python:
```
    import journal
    …
    def foo():
        …
        # make a channel
        channel = journal.info(name=“isce3.geocode”)
        # say something
        channel.log(“Hello world!”) # source, line, function name are automatically extracted from the python stack trace
```

There are five severities. Three (error, warning, info) are end-user facing, the other two (firewall, debug) are meant for developers and are optimized away for release build. Firewall and error are fatal: they raise exceptions when anything is written to them. You can make them non-fatal on a per channel basis or in bulk, or catch the exception and do something with it. Debug is the developer version of info, firewall is reserved for reporting serious constraint violations, so that a firewall that fires is an indication that the code has self-caught a bug.

Channels of the same severity+name all share a common state, across both the python and c++ codebase. This means that you can instantiate a channel in your main python script, configure it to send output to a file, and become fatal, and then access a channel by the same severity+name far away in the C++ code and have the output go to the same file without having to pass the channel around as application context. The names work best when you do a bit of namespace design for them ahead of  time. They are hierarchical, with scopes separated by dots. Something like “isce3.geocode.projection” would be a good name for a channel.

**Comment by dbekaert** [comment]
@rtburns-jpl @hfattahi Let me know in case you have other suggestions. 

@rtburns-jpl I also understand that Pyre would be good for handling GPU implementation as it has capabilities to talk and distribute across various GPU devices?

**Comment by rtburns-jpl** [comment]
This is a really nice writeup of isce's logging facilities! I might even want to steal some snippets of this for our developer documentation, if that's all right with you 👀 

It looks like you have a pretty good understanding of these, but if you have any specific questions, I'm happy to chip in with my experience/recommendations. As far as I'm aware, we're not touching the GPU parts of pyre, so I can't answer that myself, but I'll ping @aivazis to see if he has anything to say about this.

**Comment by aivazis** [comment]
Ryan,

The journal writeup was from me. Steal away.

-- Michael

**Comment by Askaholic** [comment]
So from what I can tell, `pyre` logging is basically the same as the python `logging` module, with the addition of being able to access the loggers (in `pyre` called channels) from C++ code. If we're using Cython though, AFAIK this is just as easy using the python `logging` module, so I personally would lean towards `logging` unless we are going to use some other functionality from `pyre` as well.

**Comment by dbekaert** [comment]
Added advantage would be that `pyre` is being used for NISAR ISCE3 code, so would be aligned with the SDS.
Does it add a significant dependency to have it for logging?

@rtburns-jpl open for recommendations, are there other considerations  we are missing?
Also, do i understand your earlier comment that ISCE3 might have GPU components but is not leveraging `pyre` like capabilities for scheduling/taking to GPU devices?

**Comment by rtburns-jpl** [comment]
Right now there's some pretty significant overhead having pyre as a dependency due to having to build it from source, but I think we could work with @aivazis to add binaries to conda/pypi. That's the tradeoff as I view it right now - pyre is more powerful but there's going to be some extra installation work vs. using a builtin module.

**Comment by dbekaert** [comment]
Per offline team meeting we will proceed with python logging. The ADT/SDS will refactor code upon delivery.

**Comment by dbekaert** [comment]
@Askaholic can you capture a few examples on best practice using python logging capabilties? This will also be relevant for ARIA-tools: https://github.com/aria-tools/ARIA-tools/issues/94 

```
exit code 0: nominal
exit code < 0: serious errors
exist code > 0: less serious runtime issues
```
have clear mappings of code to PGE-specific meanings allows the broader pipeline to better handle error handling. For Python, propagate exceptions so that main() can catch it and output specific information and appropriate exit codes. This allows wrappers invoking PGE code to clearly see issues that are happening deep inside the algorithm code.

    in main(), catch high level error message to output something like _error.txt
    in main(), catch stack trace to output something like _trace.txt or _exception.txt
    always use logger, with appropriate log levels. not print statements.

**Comment by Askaholic** [comment]
I see logging vs error reporting as two different issues. The former deals with how humans interact with the program while the latter deals with how other programs interact with the program. Therefore, logging is just something that we use to be able to understand what the code is doing. 

I'd say log normal messages on the "info" level and verbose messages on the "debug" level. Then we can easily turn verbose mode on/off by setting the logger level, and don't need to pass an argument around to every function.

**Comment by dbekaert** [comment]
@Askaholic perhaps we should update teh ticket, definitely referring to both items, likely my lack of using the right terminology. Lets also reach out to gerald to get some SDS perspective on the error reporting to the Raider code can easily be hooked into the production error handling.

**Comment by Askaholic** [comment]
So are you saying that error reporting is more important than logging right now? Should I be focusing on that first?

One nice thing about simply raising exceptions in python, is that if they remain unhandled, the interpreter will exit with a non-zero exit code, so even if other programs invoked it as a shell script, they will be notified of a failure in this way.

```
$ python3 -c "raise RuntimeError()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError

$ echo $?
1
```

**Comment by dbekaert** [comment]
@pymonger any thoughts on how you want the error handling done such it easily integrates in the NISAR SDS?

**Comment by Askaholic** [comment]
So as I understand it, the main issue with error reporting has to do with users being able to figure out why the program failed so that they can fix their setup appropriately. So I think kindof a mix of two things can help with this:

1. Lots of input validation which will throw exceptions with useful error message if some requirements aren't met. We want to follow a [fail fast](https://en.wikipedia.org/wiki/Fail-fast) mindset so that errors are detected at the source, and not further down the line when some intermediate data is missing.
2. Use the `logging` module and have a file handler for warning/error messages. This way, after a program has exited with a failure, the relevant exception traces/error messages should be both written to a file and printed to stdout along with the normal program output.

This should both allow a machine caller to detect errors, and report snippets from the error log back to the user.

**Comment by dbekaert** [comment]
Logging has been added under #75 . Thanks @Askaholic
