### ISSUE TITLE
Ensure that the correct number of files are written out by RAiDER for GUNW

### ISSUE THREAD

**Issue by bbuzz31** [dbekaert/RAiDER#481]
If a user (or HYP3) requests a date/time for which the weather model doesn't exist, an error is raised and caught and the raider processing continues. We might want to put into raider:calcDelaysGUNW a catch to make sure that both delay files have been successfully calculated.

@sssangha good catch raising this!

**Comment by bbuzz31** [comment]
@forrestfwilliams do you mind if I add a quick check on the number of files produced to your #480?

**Comment by forrestfwilliams** [comment]
Yep, @bbuzz31 feel free to add it!

**Comment by bbuzz31** [comment]
done in #482
