### ISSUE TITLE
[Feature/Enhancement] Use ENV Variables for HRES and ERA5 credentials in GUNW entrypoint

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#483]
The new secrets for the new weather models will need to be consumed in Raider this way.
 
@bbuzz31, this is too big a lift in the 24 hours before you go. I think this will go into the GUNW script here: https://github.com/dbekaert/RAiDER/blob/dev/tools/RAiDER/aria/prepFromGUNW.py#L231. Please provide guidance (maybe with JMaurer) where the best place to include this logic would be.
 
For HRES and ERA5, we need a way to inject env variables into the appropriate hidden files.
 
Here is how it’s done in the GUNW plugin: https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/blob/dev/isce2_topsapp/__main__.py#L53-L82 (written by Joe – note the tests: https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/blob/dev/tests/test_main.py#L6-L73)
 
The environment variables would then write to the hidden files for either ERA5 or HRES as documented nicely here: https://github.com/dbekaert/RAiDER/blob/dev/docs/WeatherModels.md

**Comment by dbekaert** [comment]
This has been added in #484
