### ISSUE TITLE
STATS: Jupyter examples

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#49]
Looking for the following notebooks (under RAiDER-docs github repo):

# Example 1 (Priority)
Get GPS information and visualize station distribution for fixed period of time 
this is inline with #11 

# Example 2
- Get GPS information and visualize delays for a fixed period in time, calculate basic statistics 
- Use the GPS station information to trigger RAiDER and compute delays
- use the RaiDER and GPS delays for basic statistical analysis.

**Comment by jlmaurer** [comment]
@sssangha in reference also to #44 the [tropo branch of my RAiDER fork](https://github.com/jlmaurer/RAiDER-1/tree/tropo) can check whether files exist for a given year and produces a .csv file with a list of years and station names and data availability. You could use this as a start to address this issue.

**Comment by dbekaert** [comment]
first version added under https://github.com/dbekaert/RAiDER-docs/pull/1
