### ISSUE TITLE
Create specified folders if they do not exist prior

### ISSUE THREAD

**Issue by jlmaurer** [dbekaert/RAiDER#5]
Right now if you specify an output folder or weather file location and it does not exist, the code errors out. Should update this to create if does not exist, because it downloads the new file anyway.

**Comment by dbekaert** [comment]
@jlmaurer ISCE developers use this, which is easier than the if conditional statements: 
```
os.makedirs(inst, exist_ok=True)
```

**Comment by jlmaurer** [comment]
PR#21 fixes this issue.
