### ISSUE TITLE
[BUG] STATS: Shapely required for raiderStats but not in environment.yml

### ISSUE THREAD

**Issue by jlmaurer** [dbekaert/RAiDER#50]
**Describe the bug**
shapely needs to be added to conda environment file requirements

**To Reproduce**
1. create a clean conda environment using the environment.yml file 
2. raiderStats.py -h
3. Traceback (most recent call last):
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/bin/raiderStats.py", line 10, in <module>
    from RAiDER.statsPlot import parseCMD
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/lib/python3.8/site-packages/RAiDER/statsPlot.py", line 10, in <module>
    from shapely.geometry import Polygon, Point
ModuleNotFoundError: No module named 'shapely'

**Expected behavior**
Print out the argparse help message

**Desktop (please complete the following information):**
 - RAiDER git tag: 559f80a68e393fa9ad3846abdcda06765ae0300c
 - Jupyter Notebook on Mac

**Comment by dbekaert** [comment]
Addressed in #52
