### ISSUE TITLE
Partial model coverage upon download - raytracing

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#508]
Scenario: With new buffering code our ask for HRRR download area  extends outside the coverage of the model. Currently we proceed and don't error out. If we let the code proceed then ray-tracing would start to have bias.

For example if more than a 5 degree buffer is requested in northern CA along the coast then we might not have enough HRRR data. https://rapidrefresh.noaa.gov/RAPv4HRRRv3-OpsTrim.jpg 

The buffering code currently is very conservative. Ideally we implement it based on actual orbit and look direction. Aka buffering does not need to be in all directions only the direction of the ray.

**Comment by bbuzz31** [comment]
I think this is closed with a number of buffering related PRs, most recently #564
