### ISSUE TITLE
HRRR producing drastically different values than PyAPS/GACOS

### ISSUE THREAD

**Issue by bbuzz31** [dbekaert/RAiDER#509]
In plots below HRRR (produced by intersecting RAiDER and running through ARIA-tools) is dramatically different than the other two delays.

Unclear whether this is in the HRRR model itself, produced by RAiDER Delay/intersection or AT

![image](https://user-images.githubusercontent.com/15522503/227743747-04ae7d98-f26e-4599-a8df-6da23774f8c1.png)

**Comment by bbuzz31** [comment]
Likely this is due to a problem in HRRR itself, as this date looks relatively okay in ERA5
![Screenshot 2023-03-28 at 14 54 39](https://user-images.githubusercontent.com/15522503/228375518-3d8036ed-e463-4bdf-a3b6-1ee4e510a74d.png)
5 from RAiDER

@jlmaurer @dbekaert any thoughts?

**Comment by jlmaurer** [comment]
@bbuzz31 interesting. Just to clarify, this is happening only for a select few datetimes or consistently at many datetimes?

**Comment by piyushrpt** [comment]
https://github.com/dbekaert/RAiDER/discussions/501#discussioncomment-5351128

I would try and make sure that lla -> model via lla on a sphere vs EPSG:4326 produces same results. If they don't it is possible that coordinates are being mapped incorrectly.  Should test just the coordinate transforms with sample points around the US

**Comment by bbuzz31** [comment]
@jlmaurer just about 3 or 4 of the 150 i checked

Thanks @piyushrpt. @jlmaurer i belive this is part of #507 ?

**Comment by jlmaurer** [comment]
That specific fix is not but I can add it.

**Comment by dbekaert** [comment]
> as this date looks relatively okay in ERA5 from RAiDER

What do you quantify as "relative ok". The plots for ARA5 shows dont  look the same for ERA5 in PyAPS verus Raider.

**Comment by dbekaert** [comment]
For HRRR suggest you walk through the model downloaded and make a vertical profile of PTe and compare it to profile of PTE of the other models. That migth also show if its in the model itself.

**Comment by dbekaert** [comment]
Im not in sync here. "Okay" is not a good quantification its very subjective. ERA 5 is the same model input and you show one to have a range 0.4 cm and the other 0.1 range.  Independent of comparing those difference between ERA5 and HRRR. Why are the difference between ERA5 itself so large...

**Comment by bbuzz31** [comment]
Closed with #566
