### ISSUE TITLE
Enhancement to not update GUNW if Weather Model is Not Available for SLC Dates

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#526]
For the ARIA-GUNW workflow, we do not want the operator to necessarily have to worry about the temporal availability of a weather model because the new GUNW will have additional layers that we still want to deliver to the DAAC even if RAIDER cannot be applied.

Examples:

1. Processing S1 data within 3 months of current date (no HRRR data will be available).
2. Processing the Aleutian Volcano chain but we can only go back to 2018 with HRRR there.

Will access weather model's instance variable `_valid_range` here: https://github.com/dbekaert/RAiDER/blob/dev/tools/RAiDER/cli/raider.py#L496

Will be very straightforward.

**Comment by dbekaert** [comment]
Ok, so you are asking for a raider function that depending on model returns validity period.

**Comment by cmarshak** [comment]
I will write this in Raider - I am just putting it as an issue so that we have a clear understanding of what needs to be done and the problem this is solving.

**Comment by cmarshak** [comment]
Sorry - to your original question, it already exists in `Raider`.

It's just

```
weather_model = HRRR()
valid_begin, valid_end = weather_model._valid_range
```
