### ISSUE TITLE
[BUG/QUESTION] weather_model._valid_date - should it be consistenly typed?

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#530]
I am working on  #529. Just noticing that certain weather models have "Present" (or a string) as their end date for the `_valid_range` property, but certain models do not.

For example:

https://github.com/dbekaert/RAiDER/blob/dev/tools/RAiDER/models/hres.py#L50 - has "Present"
https://github.com/dbekaert/RAiDER/blob/dev/tools/RAiDER/models/era5.py#L27 - has the precise end-date

All models have `_lag_time` property (in the latter case this is used to compute the end date).

Just posting this in case it's worth making sure the second date in the tuple might be made to be similar to the ERA5 case. It can be closed if nothing will be changed.

Note: not even sure how the latency of SLCs available on ASF compare to the weather models and whether this is an issue.

**Comment by jlmaurer** [comment]
@cmarshak just noting that as of #627 was merged all the end dates have been updated to be valid time zone-aware datetime objects, with datetime defaults given as well, so all typing is consistent now.
