### ISSUE TITLE
[BUG] fixture 'mocker' not found in test_intersect.py and test_GUNW.py

### ISSUE THREAD

**Issue by erik-17** [dbekaert/RAiDER#536]
while running `py.test  test/test_GUNW.py `
I get:
I turned off the first test since It takes a while to download the files and it already passed it. (However, it didnt work with GMAO but with ERA5)
![image](https://github.com/dbekaert/RAiDER/assets/114911392/78de09dc-0c13-44b6-bd9f-65cdd1a6a66c)

**Comment by bbuzz31** [comment]
think you need to install it.  `conda install -c conda-forge pytest-mock`

**Comment by jlmaurer** [comment]
> think you need to install mocker. `conda install -c conda-forge pytest-mock`

@bbuzz31 is mocker a dep we should to the RAiDER env?

**Comment by bbuzz31** [comment]
@jlmaurer this dependency is already in the env file
