### ISSUE TITLE
[BUG] BoundingBox has no _output_spacing attribute

### ISSUE THREAD

**Issue by esrivas17** [dbekaert/RAiDER#537]
Hi, 
I have been following the RAiDER-docs/notebooks/RAiDER_tutorial/RAiDER_Python_access.ipynb tutorial and Im getting the following error when running this line:
`ds,_ = tropo_delay(date_time, weather_model.out_file('weather_files'), aoi, los, height_levels=[0, 100, 500, 1000], cube_spacing_m=50)`
and also when I get rid of cube_spacing_m attribute
`ds,_ = tropo_delay(date_time, weather_model.out_file('weather_files'), aoi, los, height_levels=[0, 100, 500, 1000])`
As I show in the log file, not sure if the tutorial is out of date.
![image](https://github.com/dbekaert/RAiDER/assets/45095410/dff8f101-2144-4a89-b2b0-98335831628c)

**Comment by jlmaurer** [comment]
@bbuzz31 do you have bandwidth to check the documentation? We probably need to test all of it prior to the next RAiDER release.

**Comment by bbuzz31** [comment]
Sure I can help some over the next couple weeks. Closing this as it should be  in the notebooks github. @esrivas17 you have to add a buffer to your AOI object prior to passing it to tropo_delay. You can refer to lines 212 to 215 in `delay.py` for an example.
