### ISSUE TITLE
STATS: Simplify code structure and optimize as standalone function [enhancement]

### ISSUE THREAD

**Issue by sssangha** [dbekaert/RAiDER#54]
# Purpose
Have STATS as a standalone, independent suite of codes that can be called separately from main RAIDAR code. 

# Proposed plan of action
Will consider ways to segregate certain functions of the code into separate scripts to simplify structure and avoid having everything in a single script. Open to suggestions on how to segregate functionality (e.g. plotting in one script, variogram generation in another, preprocessor/setup in main).

**Comment by dbekaert** [comment]
This has been addressed and merged into dev
