### ISSUE TITLE
How to estimate delay(total=wet+hydro) for each pixel based on elevation of DEM ?  

### ISSUE THREAD

**Issue by mohseniaref** [dbekaert/RAiDER#553]
Hi,

As far as I concerned , we can derive delay(total=wet+hydro) for different level(height) using RAiDER. I was wondering how can we estimate pixel-wise delay according to elevation of each Pixel. Do we need to apply kind of 3D interpolation using Xarray for each pixel ?

I think the following method is simple integration all delays. we need to use something using from scipy.integrate import cumtrapz and apply integration along z for each pixel height.

```
wet_total = ds['wet_total'].values
hydro_total = ds['hydro_total'].values
total = wet_total + hydro_total
total .interp(z=500).plot()
total_delay = np.sum(total, axis=(0))
```

Best regards,
Mohammad

**Comment by bbuzz31** [comment]
Hi Mohammad, yes that is essentially correct. We do this in RAiDER automatically if you run raider with lat/lon files as AOI instead of a bounding box. Check out `test_cube_intersect` in `test_intersect.py`
