### ISSUE TITLE
HRRR bounds issue [BUG]

### ISSUE THREAD

**Issue by sssangha** [dbekaert/RAiDER#562]
**Describe the bug**
The `raider.py` program fails when I pass a `bounding_box` extent encompassing CONUS. Looks like we will have to adjust the padding behavior [here](https://github.com/dbekaert/RAiDER/blob/dev/tools/RAiDER/models/weatherModel.py#L206) but am not sure how best to proceed. Perhaps previous ticket #552 is of relevance?

**To Reproduce**
Using the attached `yaml` file, run raider:
raider.py raider.yaml

**Desktop (please complete the following information):**
 - RAiDER git tag: 9ddd4abad8414b3670194b4c08220f150d7ba00d
 - OS

[raider.yaml.txt](https://github.com/dbekaert/RAiDER/files/12009207/raider.yaml.txt)

**Comment by sssangha** [comment]
Error traceback:
```
Extent of the weather model is (xmin, ymin, xmax, ymax):-133.96, 21.14, -61.09, 47.63
Extent of the input is (xmin, ymin, xmax, ymax): -125.56, 21.44, -61.44, 47.56
/u/leffe-data/ssangha/conda_installation/stable_july30_2020/envs/RAiDER/lib/python3.10/site-packages/rasterio/__init__.py:304: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  dataset = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
Traceback (most recent call last):
  File "/u/leffe-data/ssangha/conda_installation/stable_july30_2020/envs/RAiDER/bin/raider.py", line 8, in <module>
    sys.exit(main())
  File "/u/leffe-data/ssangha/conda_installation/stable_july30_2020/RAiDER/tools/RAiDER/cli/__main__.py", line 42, in main
    process_entry_point.load()()
  File "/u/leffe-data/ssangha/conda_installation/stable_july30_2020/RAiDER/tools/RAiDER/cli/raider.py", line 316, in calcDelays
    wet_delay, hydro_delay = tropo_delay(
  File "/u/leffe-data/ssangha/conda_installation/stable_july30_2020/RAiDER/tools/RAiDER/delay.py", line 78, in tropo_delay
    ds = _get_delays_on_cube(dt, weather_model_file, wm_proj, aoi, height_levels,
  File "/u/leffe-data/ssangha/conda_installation/stable_july30_2020/RAiDER/tools/RAiDER/delay.py", line 167, in _get_delays_on_cube
    raise Exception('There are missing delay values. Check your inputs. Not writing to disk.')
Exception: There are missing delay values. Check your inputs. Not writing to disk.
```

**Comment by bbuzz31** [comment]
Because of the quirky projection in HRRR, the requested bounding box is actually outside of the model extent, which causes the nans.
In the attached image, the blue outline shows the HRRR model extent in WGS84 and the red shows the requested aoi.
Using a smaller bounding box will solve the issue.
 
![Figure_1](https://github.com/dbekaert/RAiDER/assets/15522503/4905a9cd-a2a1-41f7-bd61-83b4a10e2a0b)

**Comment by jlmaurer** [comment]
@bbuzz31 I think we should handle this type of case the same as I suggest in #563; i.e. delays get calculated for valid points and not for invalid ones (while raising a warning).
