### ISSUE TITLE
Windows does not like files with `:` in the name

### ISSUE THREAD

**Issue by Askaholic** [dbekaert/RAiDER#59]
These files are giving me "invalid path" errors on Windows:
```
wrfout_d01_2010-06-25_00:00:00
wrfplev_d01_2010-06-25_00:00:00 
```

and I think it's because of the colons. https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

![image](https://user-images.githubusercontent.com/17941539/85907921-b4bdbb80-b802-11ea-8aab-0c70b3c229db.png)

We might want to rename these if we want to support Windows users in the future.

**Comment by dbekaert** [comment]
The WRF software outputs using that filename convention.
Is there another work around that can be done for windows machines?

**Comment by Askaholic** [comment]
Can you give me a link to WRF? Maybe this is something that should be considered on their side (or is already solved in some way). If it's just a matter of WRF outputting files with this name, then that's no problem. We just rename the files. If somehow we need to feed those files back into other software which is expecting names with colons, then we'll need to think about it further.

I really don't know how you can "work around" this issue other than renaming the files. Windows simply does not allow files to have colons in the name, which means if you want the repo to be cloneable on Windows, you just can't commit any files with colons in the name.

**Comment by jlmaurer** [comment]
@dbekaert @Askaholic as I said in #60 this is only relevant for files stored in the test folder in the repo; it is irrelevant for any files that a user brings. We only need to rename the test files.

**Comment by dbekaert** [comment]
Ok has another call with @jlmaurer to catch up.

1. We rename the files with _ instead of : in the test repo. this should remove the issue to clone on windows machine.
2. For the unit test we clone, rename the file to the original WRF convention, and then will run it.
3. For our downloaded files using the API, we update to not have : or -; i.e. ERA-5 make it ERA5; merra-2 make it merra2 etc.

**Comment by Askaholic** [comment]
@dbekaert Your suggested step 2 is not possible on Windows. Windows simply does not allow you to put ":" in a filename, ever, for any file.
For example notice that the following code:
```python
>>> with open(":", "w") as f:
...     f.write("test")
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument: ':'
```
Raises an `OSError` on Windows. On Linux, or Mac this would happily create a file called ":", but the Windows file system does not allow file paths to contain certain characters, ":" being one of them. That's why git will fail to create any files with colons in the name, and hence why we shouldn't check in any such files. But the problem is not with git, it's with the Windows filesystem which affects all applications running on Windows.

Dashes are fine, the only prohibited ascii characters are:
```
    < (less than)
    > (greater than)
    : (colon)
    " (double quote)
    / (forward slash)
    \ (backslash)
    | (vertical bar or pipe)
    ? (question mark)
    * (asterisk)
```
