### ISSUE TITLE
MERRA2 processing

### ISSUE THREAD

**Issue by mohseniaref** [dbekaert/RAiDER#620]
Dear All,

I have seen following error using latest version of RAIiDER using raider.py raider.yaml as you see in the attached debug.log file for MERRA2 data processing. I have no issue while i am processing ERA5 data. I was wondering if you can help me in this regard.

Best regards,
Mohammad

[debug.log](https://github.com/dbekaert/RAiDER/files/13704437/debug.log)

**Comment by bbuzz31** [comment]
Please provide the yaml file given to raider

One quick suggestion is using the same spacing in x/y; looks like you have 0.5 for lat and 0.625 for lon

**Comment by mohseniaref** [comment]
Hi,


Many many thanks for your response. Everything works fine for ERA5 and ERA5T but same problem exist for MERRA2 and GMAO model.

I have tried to force in merra2.py code equal 0.5 but even with that trick it didn't work!

I attached my deug ,error file and yaml file

Thanks in advance for your response

Best,
Mohammad
[debug.log](https://github.com/dbekaert/RAiDER/files/13710358/debug.log)
[error.log](https://github.com/dbekaert/RAiDER/files/13710360/error.log)
[raider_adoptedtomintpy.zip](https://github.com/dbekaert/RAiDER/files/13710365/raider_adoptedtomintpy.zip)

**Comment by bbuzz31** [comment]
Can you confirm you got the same problem for GMAO?

**Comment by mohseniaref-InSAR** [comment]
Yes

**Comment by jlmaurer** [comment]
@mohseniaref-InSAR thanks for raising this issue! We are currently experiencing an issue with MERRA-2 and GMAO that their servers are no longer providing data at the same URL we were using to access data. However, your log file suggests that you were able to download data successfully. I'm not able to reproduce the error message thanks to this difference. Would you be able to provide the output of the following set of commands? 
```
python
>>> import RAiDER
>>> RAiDER.__version__
>>> import datetime
>>> dt = datetime.datetime(2020,1,1,0,0,0)
>>> from RAiDER.models.gmao import GMAO
>>> wm = GMAO()
>>> wm.setTime(dt)
>>> wm.set_latlon_bounds([38,39,-92,-91])
>>> wm.fetch('test.nc', dt)
```

**Comment by mohseniaref** [comment]
@jlmaurer Thanks for your response. No, as you noticed the topic is opened for MERRA2 data and the log file is for MERRA2 data. I have downloaded most of GMAO data in the past
As you said there is problem in server . I have tried once to download file and Maybe later try to use them in gmao.py code. 
`#!/bin/bash

# Array of dates
dates=(20141018 20141111 20141205 20141229 20150122 20150215 20150227 20150323 20150416 20150603 20150627 20150721 20150814 20150907 20151001 20160528 20160808 20160901 20161001 20161025 20161118 20161212 20170105 20170129 20170222 20170306 20170318 20170330 20170411 20170423 20170505 20170517 20170529 20170610 20170622 20170704 20170716 20170728 20170809 20170821 20170902 20170914 20170926 20171008 20171020 20171101 20171113 20171125 20171207 20180112 20180124 20180205 20180217 20180301 20180313 20180325 20180406 20180418 20180430 20180512 20180524 20180605 20180617 20180711 20180723 20180804 20180816 20180828 20180909 20181003 20181027 20181108 20181120 20181202 20181214 20181226 20190107 20190119 20190131 20190212 20190224 20190308 20190320 20190401 20190413 20190425)

# Iterate through dates
for date in "${dates[@]}"; do
  year="${date:0:4}"
  month="${date:4:2}"
  day="${date:6:2}"
  url="https://portal.nccs.nasa.gov/datashare/gmao/geos-fp/das/Y${year}/M${month}/D${day}/GEOS.fp.asm.inst3_3d_asm_Nv.${date}_0900.V01.nc4"
  
  # Download file using wget, but skip if the file already exists
  wget -nc $url
done
`

**Comment by mohseniaref** [comment]
Any news from MERRA2 or GMAO ?

**Comment by jlmaurer** [comment]
Hi @mohseniaref, sorry about the delay. I am working on trying to get at least MERRA2 working now. I think our API was just out of date. Should have a PR to test by tomorrow or so!
