### ISSUE TITLE
Replace cython with pybind11

### ISSUE THREAD

**Issue by Askaholic** [dbekaert/RAiDER#63]
One of the things that came up in the meeting with Michael Aivazis was the idea of writing python bindings using `pybind11` instead of `cython`. I think this has some merit for a few reasons.

1. This project does a lot of tasks which are highly parallelizable over multiple threads. Implementing true multithreading is probably easier in pure C++ (although cython does have functionality for it).
2. We are barely using cython in the first place and it would require minimal effort to switch over right now. 
3. The Geo2rdr code is already written in a "binding style". By that I mean, it is implemented in pure C++ and only uses cython to generate the python bindings. This is the problem which pybind11 is designed to fix.
4. If we do eventually write some GPU code, really our only option is to write that in CUDA, and then wrap it with some python bindings. Again, while this may be possible with cython, pybind11 is designed for exactly this use case.

Cons:
1. Setup might be a little harder. There is an example here https://github.com/pybind/python_example
2. Calling back to python code from the C++ code is more difficult

**Comment by dbekaert** [comment]
If it merits the change and we can make it agnostic to the user, and the install process remains as simple, i would be fine for the change.

**Comment by Askaholic** [comment]
The install process doesn’t change, and actually the dependencies don’t change either because pip will download the pybind headers automatically. Cython and pybind11 are also not mutually exclusive as it turns out. I’ve been using pybind for the c++ interpolator without porting over the cython modules.

**Comment by dbekaert** [comment]
Then i do not have any objections. @jlmaurer thoughts?

**Comment by jlmaurer** [comment]
I was just looking at [this article](http://blog.behnel.de/posts/cython-pybind11-cffi-which-tool-to-choose.html), which suggests that cython and pybind11 provide opposite perspectives on the same problem: Cython allows one to stay focused on python but write native code (more my tendency) while pybind11 is C-focused and allows the developer to bring their native  code into Python easily (probably better for incorporating lower-level APIs like CUDA as @Askaholic mentioned). So, if they conflict and are easy to use, we could start building with pybind11 as appropriate but keep the cython dependency for the time being unless we decide it's definitely not needed. I know for myself it's much easier to think in terms of optimizing python than starting in C/C++.

**Comment by jlmaurer** [comment]
Sorry I meant if they *don't* conflict. :)

**Comment by dbekaert** [comment]
Yeah that sounds good. I think we should gradually transfer. If they do not conflict we can always swap it out.

**Comment by jlmaurer** [comment]
Closing as we will maintain both cython and pybind11 for the time being.
