### ISSUE TITLE
[BUG] `test_GUNW.py`: duplicated test names

### ISSUE THREAD

**Issue by garlic-os** [dbekaert/RAiDER#668]
There are two tests in `test_GUNW.py` named `test_check_weather_model_availability`. The one that comes later in the file is overriding the earlier one and preventing it from being run. They and their related tests seem to be doing the same/similar things.

https://github.com/dbekaert/RAiDER/blob/a826e077ca29dfc70cab87081559853f4d373e69/test/test_GUNW.py#L340-L369
https://github.com/dbekaert/RAiDER/blob/a826e077ca29dfc70cab87081559853f4d373e69/test/test_GUNW.py#L658-L672

**Comment by royagrace** [comment]
This was fixed in #672.
