### ISSUE TITLE
STATS: Seaonal Amplitude analysis

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#87]

**Comment by sssangha** [comment]
We will add options to evaluate the seasonal amplitude on a station-by-station basis and for the gridded array.

@dbekaert, should we also capture phase values by (1) default, (2) by specifying a separate option, or (3) not at all. In my opinion, we either do (1) or (3) as I would aim to be conservative with options going forward where possible to not overwhelm the user. I.e. with (2) users would have to specify 4  separate flags just to plot both station-by-station and gridded plots of amplitude and phase.

**Comment by dbekaert** [comment]
@sssangha lets go with option 1.
