### ISSUE TITLE
plotting weather model debug plots.

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#88]
Adding in a capability to plot the weather model at low and higher elevation. this allows us to verify P,T,e to see if it looks as expected.

**Comment by Askaholic** [comment]
The current plotWeather file is outdated and is trying to call functions that don't exist anymore. For example:
```
AttributeError: module 'RAiDER.interpolator' has no attribute 'Interpolator'
```

**Comment by dbekaert** [comment]
@leiyangleon has been covering this
