### ISSUE TITLE
Choose a consistent bounding box format

### ISSUE THREAD

**Issue by Askaholic** [dbekaert/RAiDER#89]
Currently the bounding box is taken as an input in NWSE order, and printed out in various places in SNWE order. Needless to say this is confusing, we should pick one order and stick with it everywhere.

**Comment by sssangha** [comment]
The input for ```downloadGNSS.py``` and ```statsPlot.py``` are already expected in SNWE order. This is the convention in other packages such as ISCE and ARIA-tools, so I think we should proceed with inputs in SNWE order across the board.

**Comment by Askaholic** [comment]
Ok that sounds good. I'll go ahead and change the arg parser to use SNWE as well.
